"""
Extended Seed Molecule Database (Volume II)
============================================
Additional ~350+ aroma molecules, essential oils, absolutes, and synthetics
to supplement the core seed database. Combined, the agent has 500+ curated
molecules covering every commercially significant fragrance material.

Sources: Arctander, TGSC, PubChem, IFRA, industry catalogs, academic literature.
"""

EXTENDED_MOLECULES = [
    # ========================================================================
    # ADDITIONAL FLORAL
    # ========================================================================
    {"name": "Nerol", "cas": "106-25-2", "odor_descriptors": ["floral", "rose", "sweet", "fresh", "citrus"], "odor_families": ["floral", "citrus"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Fresh rose-citrus. Cis isomer of geraniol. Found in neroli, rose, lemon. Softer and fresher than geraniol."},
    {"name": "Rhodinol", "cas": "6812-78-8", "odor_descriptors": ["floral", "rose", "sweet", "fresh", "peony"], "odor_families": ["floral"], "formula": "C10H20O", "mw": 156.27, "volatility": "heart", "use": "FR", "notes": "Enriched citronellol fraction. The finest rose alcohol. Sweeter, more floral than standard citronellol."},
    {"name": "Dimethyl Benzyl Carbinol (DMBC)", "cas": "100-86-7", "odor_descriptors": ["floral", "lilac", "fresh", "sweet", "clean"], "odor_families": ["floral"], "formula": "C10H14O", "mw": 150.22, "volatility": "heart", "use": "FR", "notes": "Lilac and fresh floral character. Key in lilac and muguet accords."},
    {"name": "Canthoxal", "cas": "5462-06-2", "odor_descriptors": ["floral", "hawthorn", "anisic", "sweet", "fresh"], "odor_families": ["floral", "spicy"], "formula": "C11H14O2", "mw": 178.23, "volatility": "heart", "use": "FR", "notes": "Hawthorn blossom with anisic sweetness. Key in hawthorn and sweet floral accords."},
    {"name": "Majantol", "cas": "10371-08-3", "odor_descriptors": ["floral", "muguet", "fresh", "sweet", "clean"], "odor_families": ["floral"], "formula": "C12H18O2", "mw": 194.27, "volatility": "heart", "use": "FR", "notes": "Muguet-lily with clean sweetness. Lilial alternative. Non-sensitizing."},
    {"name": "Florhydral", "cas": "125109-89-3", "odor_descriptors": ["floral", "muguet", "fresh", "green", "watery"], "odor_families": ["floral", "green"], "formula": "C13H18O2", "mw": 206.28, "volatility": "heart", "use": "FR", "notes": "Fresh muguet with watery-green facets. Modern lily of the valley ingredient."},
    {"name": "Methyl Benzoate", "cas": "93-58-3", "odor_descriptors": ["floral", "ylang", "sweet", "fruity", "wintergreen"], "odor_families": ["floral", "fruity"], "formula": "C8H8O2", "mw": 136.15, "volatility": "top", "use": "FL/FR", "notes": "Ylang-ylang and fruity-floral character. Found in ylang-ylang and tuberose."},
    {"name": "Nerolidol", "cas": "7212-44-4", "odor_descriptors": ["floral", "woody", "apple", "rose", "fresh"], "odor_families": ["floral", "woody"], "formula": "C15H26O", "mw": 222.37, "volatility": "heart", "use": "FL/FR", "notes": "Floral-woody with apple-rose nuance. Found in neroli, rose, and many flowers. Good fixative."},
    {"name": "Farnesol", "cas": "4602-84-0", "odor_descriptors": ["floral", "linden", "green", "mild", "sweet"], "odor_families": ["floral", "green"], "formula": "C15H26O", "mw": 222.37, "volatility": "heart", "use": "FL/FR", "notes": "Linden blossom character. Mild, sweet, green-floral. Found in linden, rose, neroli. IFRA: sensitizer."},
    {"name": "Linalool Oxide", "cas": "1365-19-1", "odor_descriptors": ["floral", "woody", "sweet", "earthy", "fermented"], "odor_families": ["floral", "woody"], "formula": "C10H18O2", "mw": 170.25, "volatility": "top", "use": "FL/FR", "notes": "Floral-woody with earthy nuance. Found in tea, grape, passion fruit."},
    {"name": "Methoxyphenylbutanone", "cas": "104-27-8", "odor_descriptors": ["floral", "mimosa", "sweet", "fresh", "honey"], "odor_families": ["floral"], "formula": "C11H14O2", "mw": 178.23, "volatility": "heart", "use": "FR", "notes": "Mimosa and sweet floral character. Key in mimosa and sweet floral accords."},
    {"name": "Cyclal C", "cas": "432-25-7", "odor_descriptors": ["floral", "linden", "fresh", "green", "sweet"], "odor_families": ["floral", "green"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FR", "notes": "Linden blossom and fresh-green-floral. Key in linden and fresh floral accords."},
    {"name": "Mefrosol", "cas": "105-14-6", "odor_descriptors": ["floral", "linden", "fresh", "sweet", "honey"], "odor_families": ["floral"], "formula": "C9H12O2", "mw": 152.19, "volatility": "top", "use": "FR", "notes": "Linden/honey flower. Fresh-sweet-floral. Key in linden and honey-floral accords."},
    {"name": "Anisic Aldehyde", "cas": "123-11-5", "odor_descriptors": ["floral", "hawthorn", "sweet", "anisic", "powdery"], "odor_families": ["floral", "spicy"], "formula": "C8H8O3", "mw": 152.15, "volatility": "heart", "use": "FL/FR", "notes": "Hawthorn blossom with anisic sweetness. Powdery-floral. Very versatile."},
    {"name": "Tetrahydromuguol", "cas": "72926-33-5", "odor_descriptors": ["floral", "muguet", "fresh", "clean", "natural"], "odor_families": ["floral"], "formula": "C11H20O2", "mw": 184.28, "volatility": "heart", "use": "FR", "notes": "Muguet-lily of the valley. Non-sensitizing alternative to Lilial and Lyral."},
    {"name": "Peony Nitrile", "cas": "94133-92-3", "odor_descriptors": ["floral", "peony", "green", "fresh", "rosy"], "odor_families": ["floral", "green"], "formula": "C11H11N", "mw": 157.21, "volatility": "top", "use": "FR", "notes": "Peony flower character. Fresh-green-rosy. Nitrile-based (stable in bleach)."},
    {"name": "Rose Petal Nitrile", "cas": "72401-54-8", "odor_descriptors": ["floral", "rose", "green", "fresh", "metallic"], "odor_families": ["floral", "green"], "formula": "C10H11N", "mw": 145.20, "volatility": "top", "use": "FR", "notes": "Green-metallic rose character. More diffusive than geraniol. Used in fresh rose accords."},
    {"name": "Phenylacetaldehyde Dimethyl Acetal", "cas": "101-48-8", "odor_descriptors": ["floral", "hyacinth", "green", "sweet", "fresh"], "odor_families": ["floral", "green"], "formula": "C10H14O2", "mw": 166.22, "volatility": "top", "use": "FL/FR", "notes": "Stable form of phenylacetaldehyde. Hyacinth-green floral. Longer-lasting than the aldehyde."},
    {"name": "Agrumen Nitrile", "cas": "93963-40-7", "odor_descriptors": ["citrus", "floral", "fresh", "green", "lemon"], "odor_families": ["citrus", "floral"], "formula": "C11H11N", "mw": 157.21, "volatility": "top", "use": "FR", "notes": "Citrus-floral nitrile. Stable in functional products. Fresh lemon-green."},
    {"name": "Verdine", "cas": "24940-17-2", "odor_descriptors": ["floral", "hyacinth", "green", "fresh", "clean"], "odor_families": ["floral", "green"], "formula": "C12H14O3", "mw": 206.24, "volatility": "heart", "use": "FR", "notes": "Hyacinth-green floral. Clean and natural-smelling."},
    {"name": "Oxane", "cas": "10030-28-9", "odor_descriptors": ["floral", "rose", "fresh", "sweet", "green"], "odor_families": ["floral", "green"], "formula": "C10H18O2", "mw": 170.25, "volatility": "top", "use": "FR", "notes": "Fresh rose-green character. Adds sparkle to rose accords."},

    # ========================================================================
    # ADDITIONAL CITRUS
    # ========================================================================
    {"name": "Alpha-Pinene", "cas": "80-56-8", "odor_descriptors": ["pine", "citrus", "fresh", "sharp", "woody"], "odor_families": ["citrus", "woody"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Most abundant terpene in nature. Pine-citrus-fresh. Found in pine, rosemary, basil."},
    {"name": "Beta-Pinene", "cas": "127-91-3", "odor_descriptors": ["pine", "woody", "dry", "herbal", "fresh"], "odor_families": ["citrus", "woody"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Dry pine-herbal. Less sharp than alpha-pinene. Found in many essential oils."},
    {"name": "Myrcene", "cas": "123-35-3", "odor_descriptors": ["citrus", "fruity", "tropical", "balsamic", "warm"], "odor_families": ["citrus", "fruity"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Tropical-citrus-fruity. Found in bay, lemongrass, hop, mango. Key in tropical accords."},
    {"name": "Ocimene", "cas": "13877-91-3", "odor_descriptors": ["citrus", "tropical", "green", "floral", "herbal"], "odor_families": ["citrus", "green"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Tropical-green-citrus. Found in basil, mint, mango. Very diffusive."},
    {"name": "Terpinolene", "cas": "586-62-9", "odor_descriptors": ["citrus", "pine", "herbal", "fresh", "woody"], "odor_families": ["citrus", "woody"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Fresh pine-citrus-herbal. Found in tea tree, cumin, apple. Fresh top note."},
    {"name": "Alpha-Terpinyl Acetate", "cas": "80-26-2", "odor_descriptors": ["bergamot", "lavender", "fresh", "fruity", "herbal"], "odor_families": ["citrus", "aromatic_herbal"], "formula": "C12H20O2", "mw": 196.29, "volatility": "top", "use": "FL/FR", "notes": "Bergamot-lavender character. Key component of cardamom oil. Fresh fruity-herbal."},
    {"name": "Citronellal", "cas": "106-23-0", "odor_descriptors": ["citrus", "lemon", "fresh", "aldehydic", "sharp"], "odor_families": ["citrus", "aldehydic"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Intense lemon-citronella. Key in citronella oil and lemon-scented tea tree."},
    {"name": "Lime Oil Distilled (Natural)", "cas": "8008-26-2", "odor_descriptors": ["citrus", "lime", "fresh", "sharp", "tart"], "odor_families": ["citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Citrus aurantifolia. Sharp-tart lime. Distilled version loses some freshness but is phototoxicity-safe."},
    {"name": "Lemon Oil (Natural)", "cas": "8008-56-8", "odor_descriptors": ["citrus", "lemon", "fresh", "bright", "zesty"], "odor_families": ["citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Citrus limon. Bright zesty lemon. Contains citral, limonene, pinenes. Cold-pressed preferred."},
    {"name": "Sweet Orange Oil (Natural)", "cas": "8008-57-9", "odor_descriptors": ["citrus", "orange", "sweet", "fresh", "juicy"], "odor_families": ["citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Citrus sinensis. Sweet juicy orange. 90%+ limonene. The most-produced citrus oil."},
    {"name": "Grapefruit Oil (Natural)", "cas": "8016-20-4", "odor_descriptors": ["citrus", "grapefruit", "bitter", "fresh", "tropical"], "odor_families": ["citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Citrus paradisi. Bitter-fresh grapefruit. Contains nootkatone. IFRA: phototoxic (furanocoumarins)."},
    {"name": "Mandarin Oil (Natural)", "cas": "8008-31-9", "odor_descriptors": ["citrus", "mandarin", "sweet", "fresh", "fruity"], "odor_families": ["citrus", "fruity"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Citrus reticulata. Sweetest citrus oil. Contains methyl N-methyl anthranilate (unique to mandarin)."},
    {"name": "Citronella Oil (Natural)", "cas": "8000-29-1", "odor_descriptors": ["citrus", "lemon", "fresh", "grassy", "woody"], "odor_families": ["citrus", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Cymbopogon nardus. Lemon-grassy. Contains citronellal, geraniol, citronellol. Insect repellent."},
    {"name": "Terpineol", "cas": "98-55-5", "odor_descriptors": ["pine", "lilac", "floral", "fresh", "clean"], "odor_families": ["citrus", "floral"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Lilac-pine-floral. Widely used in soap perfumery. Clean-fresh character."},
    {"name": "Decyl Aldehyde (Aldehyde C-10)", "cas": "112-31-2", "odor_descriptors": ["citrus", "orange peel", "waxy", "floral", "fresh"], "odor_families": ["citrus", "aldehydic"], "formula": "C10H20O", "mw": 156.27, "volatility": "top", "use": "FL/FR", "notes": "Orange peel aldehyde. Key in Chanel No. 5 and citrus-aldehydic florals."},
    {"name": "Sabinene", "cas": "3387-41-5", "odor_descriptors": ["citrus", "pepper", "woody", "fresh", "spicy"], "odor_families": ["citrus", "spicy"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Pepper-citrus-woody. Found in black pepper, juniper, tea tree."},
    {"name": "Phellandrene Alpha", "cas": "99-83-2", "odor_descriptors": ["citrus", "pepper", "herbal", "fresh", "woody"], "odor_families": ["citrus", "spicy"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "Pepper-herbal-citrus. Found in eucalyptus, pepper, parsley."},
    {"name": "Lauric Aldehyde (Aldehyde C-12 MNA)", "cas": "112-54-9", "odor_descriptors": ["aldehydic", "soapy", "waxy", "metallic", "clean"], "odor_families": ["aldehydic"], "formula": "C12H24O", "mw": 184.32, "volatility": "top", "use": "FL/FR", "notes": "Clean metallic aldehyde. Key in aldehydic florals and modern clean compositions."},

    # ========================================================================
    # ADDITIONAL WOODY
    # ========================================================================
    {"name": "Georgywood", "cas": "122681-41-0", "odor_descriptors": ["woody", "cedar", "amber", "vetiver", "dry"], "odor_families": ["woody", "amber"], "formula": "C14H24O", "mw": 208.34, "volatility": "base", "use": "FR", "notes": "IFF. Cedar-vetiver-amber hybrid. Dry woody character. Key in modern woody-amber fragrances."},
    {"name": "Guaiaconol", "cas": "6280-33-5", "odor_descriptors": ["woody", "guaiac", "smoky", "tea", "phenolic"], "odor_families": ["woody", "leathery"], "formula": "C10H12O2", "mw": 164.20, "volatility": "heart", "use": "FR", "notes": "Guaiac-smoky-woody. Key in tea and smoky accords."},
    {"name": "Guaiacwood Oil (Natural)", "cas": "8023-11-2", "odor_descriptors": ["woody", "guaiac", "tea", "rose", "smoky", "sweet"], "odor_families": ["woody", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Bulnesia sarmientoi. Tea-like woody-rose. Overharvested—sustainability concerns. Contains guaiol, bulnesol."},
    {"name": "Cedarwood Virginia Oil (Natural)", "cas": "8000-27-9", "odor_descriptors": ["woody", "cedar", "dry", "pencil", "clean"], "odor_families": ["woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Juniperus virginiana. Dry pencil-cedar. Contains alpha-cedrene, thujopsene. Drier than Atlas cedar."},
    {"name": "Amyris Oil (Natural)", "cas": "8015-65-4", "odor_descriptors": ["woody", "cedar", "sweet", "balsamic", "soft"], "odor_families": ["woody", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Amyris balsamifera. Often called 'West Indian Sandalwood' but unrelated. Sweet woody-balsamic."},
    {"name": "Guaiacol", "cas": "90-05-1", "odor_descriptors": ["woody", "smoky", "phenolic", "medicinal", "sweet"], "odor_families": ["woody", "leathery"], "formula": "C7H8O2", "mw": 124.14, "volatility": "top", "use": "FL/FR", "notes": "Smoky-woody-phenolic. Found in roasted coffee, wood smoke. Key in smoke and leather accords."},
    {"name": "Verdox", "cas": "5435-61-0", "odor_descriptors": ["woody", "cedar", "fresh", "clean", "orvall", "grapefruit"], "odor_families": ["woody", "citrus"], "formula": "C10H18O2", "mw": 170.25, "volatility": "heart", "use": "FR", "notes": "Fresh cedar-woody. Clean and diffusive. Used in modern fresh-woody compositions."},
    {"name": "Piconia", "cas": "18368-91-7", "odor_descriptors": ["woody", "vetiver", "grapefruit", "fresh", "clean"], "odor_families": ["woody"], "formula": "C10H18O2", "mw": 170.25, "volatility": "heart", "use": "FR", "notes": "Vetiver-grapefruit-woody. Fresh woody with vetiver nuance."},
    {"name": "Woodyflor", "cas": "13720-91-7", "odor_descriptors": ["woody", "floral", "cedar", "sweet", "clean"], "odor_families": ["woody", "floral"], "formula": "C12H20O2", "mw": 196.29, "volatility": "heart", "use": "FR", "notes": "Floral-woody-cedar. Bridge between woody and floral notes."},
    {"name": "Oryclon", "cas": "58967-25-6", "odor_descriptors": ["woody", "cedar", "dry", "fresh", "clean"], "odor_families": ["woody"], "formula": "C12H22O", "mw": 182.30, "volatility": "base", "use": "FR", "notes": "Dry cedar-woody. Clean and transparent woody character."},
    {"name": "Cedryl Methyl Ether", "cas": "19870-74-6", "odor_descriptors": ["woody", "cedar", "dry", "clean", "amber"], "odor_families": ["woody", "amber"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "Dry cedar with amber warmth. Very tenacious. Cedar accent and fixative."},
    {"name": "Cedramber", "cas": "53267-26-0", "odor_descriptors": ["woody", "cedar", "amber", "warm", "dry"], "odor_families": ["woody", "amber"], "formula": "C15H26O", "mw": 222.37, "volatility": "base", "use": "FR", "notes": "Firmenich. Cedar-amber hybrid. Warm-dry-woody. Key in modern woody-amber compositions."},
    {"name": "Thujopsadienol", "cas": "41834-20-4", "odor_descriptors": ["woody", "cedar", "amber", "sweet", "rich"], "odor_families": ["woody", "amber"], "formula": "C15H24O", "mw": 220.35, "volatility": "base", "use": "FR", "notes": "Rich cedar-amber. Derived from cedarwood. Very tenacious base note."},
    {"name": "Bacdanol", "cas": "1000186-38-6", "odor_descriptors": ["woody", "sandalwood", "creamy", "sweet", "musky"], "odor_families": ["woody", "musky"], "formula": "C11H22O", "mw": 170.29, "volatility": "base", "use": "FR", "notes": "IFF. Sandalwood-musk hybrid. Creamy-sweet-woody with musk warmth."},
    {"name": "Brahmanol", "cas": "68857-61-0", "odor_descriptors": ["woody", "amber", "dry", "powdery", "clean"], "odor_families": ["woody", "amber"], "formula": "C13H24O", "mw": 196.33, "volatility": "base", "use": "FR", "notes": "Symrise. Dry woody-amber. Similar to Norlimbanol. Modern woody-amber ingredient."},
    {"name": "Patchouli Ethanone", "cas": "408335-30-4", "odor_descriptors": ["woody", "patchouli", "earthy", "sweet", "warm"], "odor_families": ["woody", "earthy"], "formula": "C14H20O2", "mw": 220.31, "volatility": "base", "use": "FR", "notes": "Woody-patchouli with sweet warmth. Modern patchouli ingredient."},
    {"name": "Kepsusine", "cas": "N/A", "odor_descriptors": ["woody", "cedar", "fresh", "clean", "minty"], "odor_families": ["woody", "green"], "formula": "N/A (proprietary)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Fresh cedar-minty character. Used in clean-woody compositions."},

    # ========================================================================
    # ADDITIONAL AMBER
    # ========================================================================
    {"name": "Amberketal", "cas": "125276-17-9", "odor_descriptors": ["amber", "warm", "rich", "dry", "mineral"], "odor_families": ["amber"], "formula": "C13H22O2", "mw": 210.31, "volatility": "base", "use": "FR", "notes": "Rich amber-mineral character. Key in modern amber and mineral accords."},
    {"name": "Ambrocenide", "cas": "129326-82-7", "odor_descriptors": ["amber", "ambroxan", "rich", "warm", "powerful"], "odor_families": ["amber"], "formula": "C20H36O2", "mw": 308.50, "volatility": "base", "use": "FR", "notes": "Symrise. Super-charged Ambroxan. 10x more potent. Extremely long-lasting ambergris."},
    {"name": "Cetalore", "cas": "31906-07-7", "odor_descriptors": ["amber", "warm", "animalic", "mineral", "sweet"], "odor_families": ["amber", "musky"], "formula": "C14H26O", "mw": 210.36, "volatility": "base", "use": "FR", "notes": "Amber-animalic-mineral. Warm sweet ambergris character."},
    {"name": "Ysampler K", "cas": "61239-46-3", "odor_descriptors": ["amber", "warm", "woody", "rich", "dry"], "odor_families": ["amber", "woody"], "formula": "C12H22O2", "mw": 198.30, "volatility": "base", "use": "FR", "notes": "Amber-woody-dry. Rich warm amber with woody nuance."},
    {"name": "Ambermore", "cas": "N/A", "odor_descriptors": ["amber", "warm", "sweet", "rich", "balsamic"], "odor_families": ["amber"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "Rich warm sweet amber. Key in modern amber and oriental accords."},
    {"name": "Ambrarome Absolute", "cas": "8015-65-4", "odor_descriptors": ["amber", "tobacco", "warm", "rich", "leathery"], "odor_families": ["amber", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Thermal decomposition of labdanum/ambrein. Rich amber-tobacco-leather."},
    {"name": "Ciste Absolute (Natural)", "cas": "N/A", "odor_descriptors": ["amber", "labdanum", "warm", "resinous", "floral"], "odor_families": ["amber", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Cistus ladaniferus flowers. Amber-labdanum with floral nuance. Richer than labdanum alone."},
    {"name": "Opoponax Resinoid (Natural)", "cas": "8021-36-1", "odor_descriptors": ["balsamic", "sweet", "woody", "amber", "myrrh"], "odor_families": ["amber"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Commiphora erythraea. Sweet-balsamic amber. Related to myrrh but sweeter. Key in oriental accords."},
    {"name": "Ambergris Tincture (Natural/Historical)", "cas": "8038-63-7", "odor_descriptors": ["ambergris", "warm", "animalic", "marine", "sweet", "tobacco"], "odor_families": ["amber", "musky"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Physeter macrocephalus (sperm whale). HISTORICAL. Now banned. Contains ambrein. All modern ambergris is synthetic (Ambroxan, Ambroxide, etc.)."},

    # ========================================================================
    # ADDITIONAL MUSKY
    # ========================================================================
    {"name": "Romandolide", "cas": "238394-55-5", "odor_descriptors": ["musk", "clean", "fresh", "fruity", "pear"], "odor_families": ["musky", "fruity"], "formula": "C16H28O3", "mw": 268.39, "volatility": "base", "use": "FR", "notes": "Firmenich. Fresh-fruity musk. Pear-like cleanliness. Modern clean musk."},
    {"name": "Helvetolide", "cas": "141776-47-8", "odor_descriptors": ["musk", "clean", "fresh", "pear", "fruity"], "odor_families": ["musky", "fruity"], "formula": "C16H30O3", "mw": 270.41, "volatility": "base", "use": "FR", "notes": "Firmenich. Pear-like fresh musk. Clean and fruity. Similar to Romandolide."},
    {"name": "Musk Ketone", "cas": "81-14-1", "odor_descriptors": ["musk", "warm", "powdery", "sweet", "animalic"], "odor_families": ["musky"], "formula": "C14H7NO4", "mw": 257.21, "volatility": "base", "use": "FR", "notes": "HISTORICAL. Nitro musk. Now severely restricted/banned (environmental persistence, toxicity). Was key in Shalimar and classic orientals."},
    {"name": "Globalide", "cas": "68901-29-3", "odor_descriptors": ["musk", "warm", "clean", "powdery", "floral"], "odor_families": ["musky"], "formula": "C17H30O2", "mw": 266.42, "volatility": "base", "use": "FR", "notes": "Macrocyclic musk. Warm-clean-powdery. Good fixative. More biodegradable than polycyclic musks."},
    {"name": "Musk MC-5", "cas": "141776-32-1", "odor_descriptors": ["musk", "clean", "powdery", "soft", "skin"], "odor_families": ["musky"], "formula": "C14H26O3", "mw": 242.36, "volatility": "base", "use": "FR", "notes": "Soft skin musk. Clean-powdery. Good in skin-scent and clean musk accords."},
    {"name": "Astrosone", "cas": "91381-38-7", "odor_descriptors": ["musk", "warm", "powdery", "clean", "floral"], "odor_families": ["musky"], "formula": "C15H28O3", "mw": 256.38, "volatility": "base", "use": "FR", "notes": "IFF. Warm powdery musk. Clean-floral-musky. Good for powder room accords."},
    {"name": "Musk 89-90", "cas": "N/A", "odor_descriptors": ["musk", "warm", "animalic", "natural", "skin"], "odor_families": ["musky"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "Warm animalic musk. Natural-smelling skin musk character."},
    {"name": "Muscone", "cas": "541-91-3", "odor_descriptors": ["musk", "warm", "animalic", "skin", "natural", "elegant"], "odor_families": ["musky"], "formula": "C16H30O", "mw": 238.41, "volatility": "base", "use": "FR", "notes": "The natural musk ketone from musk deer. Now synthetic. The most animalic musk. Extremely expensive natural. Key in classic chypre and oriental."},
    {"name": "Musk A (Astratone)", "cas": "68966-81-2", "odor_descriptors": ["musk", "warm", "powdery", "sweet", "clean"], "odor_families": ["musky"], "formula": "C15H22O3", "mw": 250.34, "volatility": "base", "use": "FR", "notes": "Warm powdery musk. Sweet-clean. Used in fine fragrance and functional perfumery."},
    {"name": "Cervolide", "cas": "67088-29-5", "odor_descriptors": ["musk", "clean", "fresh", "soapy", "sweet"], "odor_families": ["musky"], "formula": "C14H26O3", "mw": 242.36, "volatility": "base", "use": "FR", "notes": "Clean fresh musk. Soapy-sweet. Good for clean laundry and fresh compositions."},

    # ========================================================================
    # ADDITIONAL SPICY
    # ========================================================================
    {"name": "Nutmeg Oil (Natural)", "cas": "8008-45-5", "odor_descriptors": ["spicy", "nutmeg", "warm", "woody", "fresh"], "odor_families": ["spicy", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Myristica fragrans. Warm spicy-woody. Contains sabinene, alpha-pinene, myristicin."},
    {"name": "Mace Oil (Natural)", "cas": "8008-45-5", "odor_descriptors": ["spicy", "mace", "warm", "aromatic", "fresh"], "odor_families": ["spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Myristica fragrans aril. Warmer, more aromatic than nutmeg seed oil."},
    {"name": "Cassia Oil (Natural)", "cas": "8007-80-5", "odor_descriptors": ["spicy", "cinnamon", "sweet", "strong", "balsamic"], "odor_families": ["spicy", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Cinnamomum cassia. Very strong cinnamon. Contains 85%+ cinnamaldehyde. IFRA: severely restricted."},
    {"name": "Pimenta Berry Oil (Natural)", "cas": "8006-77-7", "odor_descriptors": ["spicy", "allspice", "warm", "clove", "cinnamon"], "odor_families": ["spicy", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Pimenta officinalis. Allspice character. Warm-spicy-clove-cinnamon. Contains eugenol."},
    {"name": "Coriander Oil (Natural)", "cas": "8008-52-4", "odor_descriptors": ["spicy", "coriander", "citrus", "herbal", "floral"], "odor_families": ["spicy", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Coriandrum sativum. Citrus-spicy-floral. Contains linalool (70%+), decyl aldehyde."},
    {"name": "Star Anise Oil (Natural)", "cas": "8007-70-3", "odor_descriptors": ["spicy", "anise", "sweet", "warm", "licorice"], "odor_families": ["spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Illicium verum. Anise-sweet-licorice. Contains 85%+ anethole. Key in pastis and anisic compositions."},
    {"name": "Turmeric Oil (Natural)", "cas": "8024-37-1", "odor_descriptors": ["spicy", "turmeric", "earthy", "warm", "woody"], "odor_families": ["spicy", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Curcuma longa. Warm-spicy-earthy. Contains turmerone, ar-turmerone. Key in curry and oriental spice accords."},
    {"name": "Isoamyl Salicylate", "cas": "87-20-7", "odor_descriptors": ["spicy", "clove", "floral", "orchid", "sweet"], "odor_families": ["spicy", "floral"], "formula": "C12H16O3", "mw": 208.25, "volatility": "heart", "use": "FL/FR", "notes": "Orchid-clove-floral. Sweet and slightly spicy. Key in orchid and sweet-spicy floral accords."},
    {"name": "Cuminaldehyde", "cas": "122-03-2", "odor_descriptors": ["spicy", "cumin", "green", "fatty", "sharp"], "odor_families": ["spicy", "green"], "formula": "C10H12O", "mw": 148.20, "volatility": "top", "use": "FL/FR", "notes": "Cumin character. Sharp-spicy-green. Key component of cumin oil."},
    {"name": "Caraway Oil (Natural)", "cas": "8000-42-8", "odor_descriptors": ["spicy", "caraway", "herbal", "fresh", "warm"], "odor_families": ["spicy", "aromatic_herbal"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Carum carvi. Contains d-carvone (60%+). Warm-herbal-spicy."},

    # ========================================================================
    # ADDITIONAL GREEN
    # ========================================================================
    {"name": "Galbascone", "cas": "67801-20-1", "odor_descriptors": ["green", "galbanum", "fresh", "fruity", "tropical"], "odor_families": ["green", "fruity"], "formula": "C11H18O", "mw": 166.26, "volatility": "top", "use": "FR", "notes": "IFF. Galbanum-green with fruity nuance. Modern galbanum alternative. Key in green accords."},
    {"name": "Physeol", "cas": "91754-08-0", "odor_descriptors": ["green", "fig leaf", "fresh", "natural", "coconut"], "odor_families": ["green", "fruity"], "formula": "C10H20O2", "mw": 172.27, "volatility": "top", "use": "FR", "notes": "Fig leaf-green character. Natural-smelling. Key in fig and green compositions."},
    {"name": "Styralyl Acetate", "cas": "93-92-5", "odor_descriptors": ["green", "gardenia", "fresh", "fruity", "sweet"], "odor_families": ["green", "floral"], "formula": "C10H12O2", "mw": 164.20, "volatility": "top", "use": "FL/FR", "notes": "Gardenia-green character. Sweet fruity-green. Key in gardenia and green floral accords."},
    {"name": "trans-2-Hexenal (Leaf Aldehyde)", "cas": "6728-26-3", "odor_descriptors": ["green", "leaf", "sharp", "fresh", "apple"], "odor_families": ["green"], "formula": "C6H10O", "mw": 98.14, "volatility": "top", "use": "FL/FR", "notes": "Sharp green-leaf character. Found in green leaves and apples. Very powerful."},
    {"name": "cis-3-Hexenyl Acetate", "cas": "3681-71-8", "odor_descriptors": ["green", "banana", "fresh", "leaf", "sweet"], "odor_families": ["green", "fruity"], "formula": "C8H14O2", "mw": 142.20, "volatility": "top", "use": "FL/FR", "notes": "Green-leafy with banana sweetness. Found in green banana, fresh leaves."},
    {"name": "cis-3-Hexenyl Salicylate", "cas": "65405-77-8", "odor_descriptors": ["green", "sweet", "floral", "leaf", "fresh"], "odor_families": ["green", "floral"], "formula": "C13H20O3", "mw": 224.30, "volatility": "heart", "use": "FR", "notes": "Sweet green-floral. Long-lasting green note. Key in green-floral accords."},
    {"name": "Phenylacetaldehyde", "cas": "122-78-1", "odor_descriptors": ["floral", "hyacinth", "green", "honey", "sharp"], "odor_families": ["floral", "green"], "formula": "C8H8O", "mw": 120.15, "volatility": "top", "use": "FL/FR", "notes": "Hyacinth and narcissus character. Very powerful. Key in hyacinth and green floral accords."},
    {"name": "Heptanal (Aldehyde C-7)", "cas": "111-71-7", "odor_descriptors": ["green", "fatty", "fresh", "aldehydic", "sharp"], "odor_families": ["green", "aldehydic"], "formula": "C7H14O", "mw": 114.19, "volatility": "top", "use": "FL/FR", "notes": "Fatty-green aldehyde. Sharp fresh character. Used in green and aldehydic accords."},
    {"name": "Figuer Nitrile", "cas": "93963-41-8", "odor_descriptors": ["green", "fig", "fresh", "coconut", "tropical"], "odor_families": ["green", "fruity"], "formula": "C11H11N", "mw": 157.21, "volatility": "top", "use": "FR", "notes": "Fig leaf character. Green-coconut-tropical. Nitrile-based (stable in bleach). Key in fig accords."},

    # ========================================================================
    # ADDITIONAL FRUITY
    # ========================================================================
    {"name": "Ethyl Butyrate", "cas": "105-54-4", "odor_descriptors": ["fruity", "pineapple", "sweet", "fresh", "apple"], "odor_families": ["fruity"], "formula": "C6H12O2", "mw": 116.16, "volatility": "top", "use": "FL/FR", "notes": "Pineapple-apple-fruity. Very volatile. Key in fruity and tropical top notes."},
    {"name": "Isoamyl Acetate", "cas": "123-92-2", "odor_descriptors": ["fruity", "banana", "sweet", "fresh", "pear"], "odor_families": ["fruity"], "formula": "C7H14O2", "mw": 130.19, "volatility": "top", "use": "FL/FR", "notes": "THE banana molecule. Very powerful and volatile. Found in bananas and pear drops."},
    {"name": "Allyl Cyclohexyl Propionate", "cas": "2705-87-5", "odor_descriptors": ["fruity", "pineapple", "sweet", "fresh", "tropical"], "odor_families": ["fruity"], "formula": "C12H18O2", "mw": 194.27, "volatility": "top", "use": "FR", "notes": "Pineapple-tropical fruity. Very diffusive. Key in pineapple and tropical accords."},
    {"name": "Diethyl Malonate", "cas": "105-53-3", "odor_descriptors": ["fruity", "apple", "sweet", "fresh", "green"], "odor_families": ["fruity", "green"], "formula": "C7H12O4", "mw": 160.17, "volatility": "top", "use": "FL/FR", "notes": "Apple-fruity with green nuance. Used in apple and fresh fruity accords."},
    {"name": "Ethyl 2-Methyl Butyrate", "cas": "7452-79-1", "odor_descriptors": ["fruity", "apple", "sweet", "sharp", "fresh"], "odor_families": ["fruity"], "formula": "C7H14O2", "mw": 130.19, "volatility": "top", "use": "FL/FR", "notes": "Sharp-sweet apple. Very powerful. Key in apple and fruit reconstructions."},
    {"name": "Gamma-Decalactone", "cas": "706-14-9", "odor_descriptors": ["fruity", "peach", "sweet", "creamy", "apricot"], "odor_families": ["fruity", "gourmand"], "formula": "C10H18O2", "mw": 170.25, "volatility": "heart", "use": "FL/FR", "notes": "Peach-apricot lactone. Creamy-sweet-fruity. Found in peach and apricot."},
    {"name": "Delta-Decalactone", "cas": "705-86-6", "odor_descriptors": ["fruity", "peach", "creamy", "sweet", "coconut"], "odor_families": ["fruity", "gourmand"], "formula": "C10H18O2", "mw": 170.25, "volatility": "heart", "use": "FL/FR", "notes": "Creamy peach-coconut. Richer and creamier than gamma-decalactone."},
    {"name": "Delta-Dodecalactone", "cas": "713-95-1", "odor_descriptors": ["fruity", "peach", "creamy", "sweet", "buttery"], "odor_families": ["fruity", "gourmand"], "formula": "C12H22O2", "mw": 198.30, "volatility": "heart", "use": "FL/FR", "notes": "Creamy peach-butter. Very rich and long-lasting fruity lactone."},
    {"name": "Massoia Lactone", "cas": "51084-16-7", "odor_descriptors": ["fruity", "coconut", "sweet", "creamy", "tropical"], "odor_families": ["fruity", "gourmand"], "formula": "C10H16O2", "mw": 168.23, "volatility": "heart", "use": "FR", "notes": "Coconut-creamy-tropical. From Massoia bark. Very tenacious. Key in tropical and coconut accords."},
    {"name": "Wine Lactone", "cas": "182690-52-8", "odor_descriptors": ["fruity", "sweet", "coconut", "tropical", "wine"], "odor_families": ["fruity", "gourmand"], "formula": "C10H16O2", "mw": 168.23, "volatility": "heart", "use": "FR", "notes": "Extremely potent coconut-wine character. Found in white wine. One of the most potent odorants known."},
    {"name": "Allyl Amyl Glycolate", "cas": "67634-00-8", "odor_descriptors": ["fruity", "pineapple", "green", "fresh", "tropical"], "odor_families": ["fruity", "green"], "formula": "C10H18O3", "mw": 186.25, "volatility": "top", "use": "FR", "notes": "Pineapple-green. Very diffusive. Key in tropical and pineapple accords."},
    {"name": "Fructone", "cas": "6413-10-1", "odor_descriptors": ["fruity", "apple", "fresh", "sweet", "clean"], "odor_families": ["fruity"], "formula": "C8H14O4", "mw": 174.19, "volatility": "top", "use": "FL/FR", "notes": "Fresh apple-fruity. Light, clean fruity character."},
    {"name": "Aldehyde C-16 (Strawberry)", "cas": "77-83-8", "odor_descriptors": ["strawberry", "fruity", "sweet", "caramel"], "odor_families": ["fruity", "gourmand"], "formula": "C12H14O3", "mw": 206.24, "volatility": "heart", "use": "FL/FR", "notes": "Strawberry note despite 'aldehyde' name. Key in strawberry and fruity accords."},
    {"name": "Cassis Nitrile", "cas": "93963-38-3", "odor_descriptors": ["fruity", "blackcurrant", "green", "tropical", "catty"], "odor_families": ["fruity", "green"], "formula": "C11H11N", "mw": 157.21, "volatility": "top", "use": "FR", "notes": "Blackcurrant-catty-green. Nitrile (stable in bleach). Key in cassis accords."},
    {"name": "Isobutyl Quinoline (IBQ)", "cas": "93-19-6", "odor_descriptors": ["leather", "earthy", "nutty", "smoky", "green"], "odor_families": ["leathery", "earthy"], "formula": "C13H15N", "mw": 185.27, "volatility": "heart", "use": "FR", "notes": "THE leather molecule. Earthy-leather-nutty. Key in Cuir de Russie."},

    # ========================================================================
    # ADDITIONAL GOURMAND
    # ========================================================================
    {"name": "Acetoin", "cas": "513-86-0", "odor_descriptors": ["buttery", "creamy", "sweet", "dairy", "warm"], "odor_families": ["gourmand"], "formula": "C4H8O2", "mw": 88.11, "volatility": "top", "use": "FL/FR", "notes": "Buttery-creamy. Found in butter, apple, yogurt. Key in butter and dairy accords."},
    {"name": "Diacetyl", "cas": "431-03-8", "odor_descriptors": ["buttery", "creamy", "strong", "dairy"], "odor_families": ["gourmand"], "formula": "C4H6O2", "mw": 86.09, "volatility": "top", "use": "FL/FR", "notes": "Intense butter character. SAFETY: lung hazard (popcorn lung). IFRA restricted. Used at very low levels."},
    {"name": "Cyclotene (Maple Lactone)", "cas": "80-71-7", "odor_descriptors": ["maple", "caramel", "sweet", "warm", "sugar"], "odor_families": ["gourmand"], "formula": "C6H8O3", "mw": 128.13, "volatility": "heart", "use": "FL/FR", "notes": "Maple-caramel character. Key in maple and caramel accords."},
    {"name": "Sotolone", "cas": "28664-80-8", "odor_descriptors": ["caramel", "curry", "sweet", "maple", "fenugreek"], "odor_families": ["gourmand", "spicy"], "formula": "C6H8O3", "mw": 128.13, "volatility": "heart", "use": "FL/FR", "notes": "Curry-caramel-fenugreek. Extremely potent. Found in aged rum, curry, maple syrup. Key in fenugreek and curry accords."},
    {"name": "Methyl Cyclopentenolone", "cas": "80-71-7", "odor_descriptors": ["caramel", "maple", "sweet", "warm", "sugar"], "odor_families": ["gourmand"], "formula": "C6H8O2", "mw": 112.13, "volatility": "heart", "use": "FL/FR", "notes": "Caramel-maple sweetness. Found in caramelized sugar. Key in gourmand and caramel accords."},
    {"name": "Propenyl Guaethol (Vanitrope)", "cas": "94-86-0", "odor_descriptors": ["vanilla", "sweet", "warm", "clove", "spicy"], "odor_families": ["gourmand", "spicy"], "formula": "C11H14O2", "mw": 178.23, "volatility": "base", "use": "FL/FR", "notes": "Vanilla-clove character. Not true vanilla but vanillic-clove. Key in vanilla-spice accords."},
    {"name": "Coffee Furanone", "cas": "3658-77-3", "odor_descriptors": ["roasted", "coffee", "sweet", "caramel", "nutty"], "odor_families": ["gourmand"], "formula": "C6H8O3", "mw": 128.13, "volatility": "heart", "use": "FL/FR", "notes": "Roasted-coffee sweetness. Found in coffee, roasted nuts. Key in coffee and roasted accords."},
    {"name": "Honey Absolute (Natural)", "cas": "8028-66-8", "odor_descriptors": ["honey", "sweet", "floral", "warm", "beeswax"], "odor_families": ["gourmand", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Honey-beeswax character. Sweet-floral-warm. Key in honey accords."},
    {"name": "Acetyl Propionyl", "cas": "600-14-6", "odor_descriptors": ["caramel", "sweet", "buttery", "fruity"], "odor_families": ["gourmand"], "formula": "C5H8O2", "mw": 100.12, "volatility": "top", "use": "FL/FR", "notes": "Caramel-buttery sweetness. Key in caramel and butterscotch accords."},
    {"name": "Ethyl Vanillin", "cas": "121-32-4", "odor_descriptors": ["vanilla", "sweet", "gourmand", "intense", "creamy"], "odor_families": ["gourmand", "amber"], "formula": "C9H10O3", "mw": 166.17, "volatility": "base", "use": "FL/FR", "notes": "2-3x stronger than vanillin. The most intense vanilla molecule. Key in gourmand and oriental accords."},

    # ========================================================================
    # ADDITIONAL AQUATIC
    # ========================================================================
    {"name": "Profundal", "cas": "N/A", "odor_descriptors": ["marine", "deep", "fresh", "watery", "clean"], "odor_families": ["aquatic"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Deep marine character. Fresh-watery-clean. Used in aquatic and marine compositions."},
    {"name": "Cascalone", "cas": "108953-27-1", "odor_descriptors": ["watermelon", "fresh", "aquatic", "fruity", "clean"], "odor_families": ["aquatic", "fruity"], "formula": "C11H18O2", "mw": 182.26, "volatility": "top", "use": "FR", "notes": "Watermelon-aquatic. Fresher and more fruity than Calone. Key in modern aquatic compositions."},
    {"name": "Ozone Nitrile", "cas": "93963-40-7", "odor_descriptors": ["ozone", "fresh", "clean", "aquatic", "metallic"], "odor_families": ["aquatic", "aldehydic"], "formula": "C11H11N", "mw": 157.21, "volatility": "top", "use": "FR", "notes": "Ozone-fresh-aquatic. Nitrile (stable in bleach). Clean-metallic-aquatic."},
    {"name": "Seaweed Absolute (Natural)", "cas": "8008-64-6", "odor_descriptors": ["marine", "iodine", "green", "seaweed", "ocean"], "odor_families": ["aquatic", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Marine-green-iodine character. Key in realistic marine and ocean accords."},
    {"name": "Melonal", "cas": "59-23-0", "odor_descriptors": ["melon", "fresh", "green", "aquatic", "tropical"], "odor_families": ["aquatic", "green"], "formula": "C9H16O", "mw": 140.23, "volatility": "top", "use": "FR", "notes": "THE melon molecule. Fresh-green-melon. Very powerful. Key in melon and fresh-tropical accords."},

    # ========================================================================
    # ADDITIONAL AROMATIC / HERBAL
    # ========================================================================
    {"name": "Camphor", "cas": "76-22-2", "odor_descriptors": ["camphoraceous", "medicinal", "fresh", "cool", "sharp"], "odor_families": ["aromatic_herbal"], "formula": "C10H16O", "mw": 152.23, "volatility": "top", "use": "FR", "notes": "Classic camphor. Medicinal-cool-sharp. Found in camphor tree, rosemary, lavender."},
    {"name": "Borneol", "cas": "507-70-0", "odor_descriptors": ["camphoraceous", "herbal", "woody", "dry", "earthy"], "odor_families": ["aromatic_herbal", "woody"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Dry camphor-herbal-woody. Found in rosemary, thyme, camphor."},
    {"name": "Bornyl Acetate", "cas": "76-49-3", "odor_descriptors": ["pine", "camphor", "fresh", "herbal", "coniferous"], "odor_families": ["aromatic_herbal", "woody"], "formula": "C12H20O2", "mw": 196.29, "volatility": "top", "use": "FL/FR", "notes": "Pine-coniferous-fresh. Key in pine and conifer reconstructions."},
    {"name": "Thymol", "cas": "89-83-8", "odor_descriptors": ["herbal", "thyme", "warm", "medicinal", "spicy"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "C10H14O", "mw": 150.22, "volatility": "top", "use": "FL/FR", "notes": "Thyme character. Warm-herbal-medicinal. Key in thyme and herbal-spicy accords."},
    {"name": "Carvacrol", "cas": "499-75-2", "odor_descriptors": ["herbal", "oregano", "warm", "spicy", "pungent"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "C10H14O", "mw": 150.22, "volatility": "top", "use": "FL/FR", "notes": "Oregano character. Warm-pungent-herbal. Isomer of thymol. Key in oregano and herbal-spicy accords."},
    {"name": "Tarragon Oil (Natural)", "cas": "8016-88-4", "odor_descriptors": ["herbal", "anise", "fresh", "warm", "estragon"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Artemisia dracunculus. Anise-herbal-fresh. Contains estragole (methyl chavicol). Key in fougère and herbal accords."},
    {"name": "Angelica Root Oil (Natural)", "cas": "8015-65-4", "odor_descriptors": ["earthy", "herbal", "musky", "green", "woody"], "odor_families": ["aromatic_herbal", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Angelica archangelica. Earthy-herbal-musky. Contains pentadecanolide (musk). Key in chypre and earthy accords."},
    {"name": "Myrtle Oil (Natural)", "cas": "8008-82-6", "odor_descriptors": ["herbal", "fresh", "camphor", "sweet", "eucalyptus"], "odor_families": ["aromatic_herbal"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Myrtus communis. Fresh-herbal-camphor. Mediterranean character. Key in cologne and fresh-herbal accords."},
    {"name": "Juniper Berry Oil (Natural)", "cas": "8002-75-3", "odor_descriptors": ["fresh", "woody", "gin", "spicy", "coniferous"], "odor_families": ["aromatic_herbal", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Juniperus communis. Fresh-gin-woody. Contains alpha-pinene, sabinene. Key in gin and fresh-woody accords."},
    {"name": "Fennel Oil Bitter (Natural)", "cas": "8006-84-6", "odor_descriptors": ["herbal", "anise", "sweet", "fresh", "spicy"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Foeniculum vulgare. Anise-herbal-sweet. Contains trans-anethole, fenchone."},
    {"name": "Dill Oil (Natural)", "cas": "8006-75-5", "odor_descriptors": ["herbal", "dill", "fresh", "green", "caraway"], "odor_families": ["aromatic_herbal", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Anethum graveolens. Fresh-herbal-green. Contains carvone, limonene. Key in culinary and green-herbal accords."},
    {"name": "Chamomile Roman Oil (Natural)", "cas": "8002-66-2", "odor_descriptors": ["herbal", "sweet", "fruity", "apple", "calm"], "odor_families": ["aromatic_herbal", "fruity"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Chamaemelum nobile. Sweet-apple-herbal. Contains angelic acid esters. Calming. Key in herbal-sweet accords."},
    {"name": "Wormwood Oil (Natural)", "cas": "8008-93-3", "odor_descriptors": ["herbal", "bitter", "absinthe", "fresh", "spicy"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Artemisia absinthium. Bitter-herbal-absinthe. Contains thujone (regulated). Key in absinthe and bitter-herbal accords."},
    {"name": "Lovage Oil (Natural)", "cas": "8016-75-1", "odor_descriptors": ["herbal", "celery", "green", "earthy", "spicy"], "odor_families": ["aromatic_herbal", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Levisticum officinale. Celery-herbal-green. Contains ligustilide. Key in celery and green-herbal accords."},
    {"name": "Methyl Chavicol (Estragole)", "cas": "140-67-0", "odor_descriptors": ["herbal", "anise", "fresh", "sweet", "basil"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "C10H12O", "mw": 148.20, "volatility": "top", "use": "FL/FR", "notes": "Basil-anise-fresh. Found in basil, tarragon. IFRA: restricted (potential carcinogen). Key in basil accords."},

    # ========================================================================
    # ADDITIONAL POWDERY
    # ========================================================================
    {"name": "Methyl Naphthyl Ketone", "cas": "94-92-8", "odor_descriptors": ["orange blossom", "powdery", "floral", "sweet", "metallic"], "odor_families": ["powdery", "floral"], "formula": "C12H10O", "mw": 170.21, "volatility": "heart", "use": "FR", "notes": "Orange blossom-powdery. Sweet metallic-floral. Very stable. Key in orange blossom and powdery accords."},
    {"name": "Diphenyl Oxide", "cas": "101-84-8", "odor_descriptors": ["geranium", "metallic", "floral", "fresh", "green"], "odor_families": ["powdery", "floral"], "formula": "C12H10O", "mw": 170.21, "volatility": "heart", "use": "FR", "notes": "Geranium-metallic-floral. Key in geranium reconstructions and functional perfumery."},
    {"name": "Acetophenone", "cas": "98-86-2", "odor_descriptors": ["sweet", "floral", "hawthorn", "orange blossom", "powdery"], "odor_families": ["powdery", "floral"], "formula": "C8H8O", "mw": 120.15, "volatility": "heart", "use": "FL/FR", "notes": "Hawthorn-orange blossom. Sweet-powdery-floral. Found in labdanum, castoreum."},
    {"name": "Para-Cresyl Methyl Ether", "cas": "104-93-8", "odor_descriptors": ["ylang", "floral", "narcissus", "sweet", "animalic"], "odor_families": ["powdery", "floral"], "formula": "C8H10O", "mw": 122.16, "volatility": "top", "use": "FR", "notes": "Ylang-narcissus with animalic depth. Key in ylang and narcissus accords. Very powerful."},
    {"name": "Naphthyl Ethyl Ether", "cas": "93-18-5", "odor_descriptors": ["orange blossom", "grape", "sweet", "floral", "powdery"], "odor_families": ["powdery", "floral"], "formula": "C12H12O", "mw": 172.22, "volatility": "heart", "use": "FR", "notes": "Orange blossom-grape character. Sweet-floral-powdery. Used in orange blossom and grape accords."},

    # ========================================================================
    # ADDITIONAL LEATHERY
    # ========================================================================
    {"name": "Para-Cresol", "cas": "106-44-5", "odor_descriptors": ["leather", "smoky", "tar", "horse", "phenolic"], "odor_families": ["leathery"], "formula": "C7H8O", "mw": 108.14, "volatility": "top", "use": "FR", "notes": "Sharp leather-tar character. Found in castoreum, birch tar. Extremely powerful. Use at trace."},
    {"name": "Para-Cresyl Phenyl Acetate", "cas": "101-94-0", "odor_descriptors": ["leather", "animalic", "warm", "narcissus", "honey"], "odor_families": ["leathery", "floral"], "formula": "C15H14O2", "mw": 226.27, "volatility": "heart", "use": "FR", "notes": "Leather-animalic with narcissus-honey nuance. Key in leather and narcissus accords."},
    {"name": "Cade Oil (Natural)", "cas": "8013-10-3", "odor_descriptors": ["smoky", "tar", "leather", "woody", "medicinal"], "odor_families": ["leathery", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Juniperus oxycedrus. Smoky-tar-leather. Used in leather and smoky accords. IFRA: restricted (PAHs)."},
    {"name": "Saffraleine", "cas": "68966-90-9", "odor_descriptors": ["leather", "saffron", "spicy", "tobacco", "warm"], "odor_families": ["leathery", "spicy"], "formula": "C13H13NO", "mw": 199.25, "volatility": "heart", "use": "FR", "notes": "Givaudan. Leather-saffron hybrid. Warm-spicy-leather. Key in modern leather accords."},
    {"name": "Tobacco Absolute (Natural)", "cas": "8016-42-4", "odor_descriptors": ["tobacco", "warm", "honey", "leather", "rich"], "odor_families": ["leathery", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Nicotiana tabacum. Rich-tobacco-honey-leather. Key in tobacco and leathery-gourmand accords."},

    # ========================================================================
    # ADDITIONAL ALDEHYDIC
    # ========================================================================
    {"name": "Tridecanal (Aldehyde C-13)", "cas": "10486-19-8", "odor_descriptors": ["waxy", "citrus", "fresh", "grapefruit", "soapy"], "odor_families": ["aldehydic", "citrus"], "formula": "C13H26O", "mw": 198.34, "volatility": "top", "use": "FL/FR", "notes": "Waxy-grapefruit aldehyde. Fresh-citrus-soapy. Key in aldehydic and citrus-floral accords."},
    {"name": "Myristic Aldehyde (Aldehyde C-14)", "cas": "124-25-4", "odor_descriptors": ["waxy", "soapy", "clean", "fatty", "amber"], "odor_families": ["aldehydic"], "formula": "C14H28O", "mw": 212.37, "volatility": "top", "use": "FR", "notes": "Waxy-soapy-clean. Fatty amber nuance. Used in aldehydic and clean accords."},
    {"name": "Octanal (Aldehyde C-8)", "cas": "124-13-0", "odor_descriptors": ["aldehydic", "fatty", "orange", "soapy", "waxy"], "odor_families": ["aldehydic", "citrus"], "formula": "C8H16O", "mw": 128.21, "volatility": "top", "use": "FL/FR", "notes": "Fatty-orange aldehyde. Key in citrus reconstructions and aldehydic compositions."},
    {"name": "Hexanal (Aldehyde C-6)", "cas": "66-25-1", "odor_descriptors": ["green", "fatty", "fresh", "aldehydic", "sharp"], "odor_families": ["aldehydic", "green"], "formula": "C6H12O", "mw": 100.16, "volatility": "top", "use": "FL/FR", "notes": "Green-fatty aldehyde. Sharp-fresh. Found in green leaves and grass."},
    {"name": "Karanal", "cas": "164094-75-7", "odor_descriptors": ["aldehydic", "amber", "metallic", "clean", "fresh"], "odor_families": ["aldehydic", "amber"], "formula": "C13H22O2", "mw": 210.31, "volatility": "top", "use": "FR", "notes": "IFF. Aldehydic-amber-metallic. Very powerful. Key in modern aldehydic compositions."},
    {"name": "2-Methyl Undecanal (Aldehyde C-12 MOF)", "cas": "110-41-8", "odor_descriptors": ["aldehydic", "soapy", "metallic", "amber", "waxy"], "odor_families": ["aldehydic", "amber"], "formula": "C12H24O", "mw": 184.32, "volatility": "top", "use": "FR", "notes": "Metallic-amber aldehyde. Key in Chanel No. 5. Use at trace for 'champagne fizz'."},

    # ========================================================================
    # ADDITIONAL EARTHY
    # ========================================================================
    {"name": "Cepes Absolute (Natural)", "cas": "N/A", "odor_descriptors": ["mushroom", "earthy", "rich", "woody", "umami"], "odor_families": ["earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Boletus edulis. Mushroom-earthy-woody. Key in earthy and mushroom accords."},
    {"name": "Humulene (Alpha-Caryophyllene)", "cas": "6753-98-6", "odor_descriptors": ["earthy", "woody", "hoppy", "herbal", "spicy"], "odor_families": ["earthy", "woody"], "formula": "C15H24", "mw": 204.35, "volatility": "heart", "use": "FL/FR", "notes": "Woody-hoppy-earthy. Found in hops, sage, ginger. Key in hop and earthy accords."},
    {"name": "Octahydronaphthalenone", "cas": "27784-78-1", "odor_descriptors": ["earthy", "woody", "musty", "patchouli", "damp"], "odor_families": ["earthy", "woody"], "formula": "C10H14O", "mw": 150.22, "volatility": "base", "use": "FR", "notes": "Earthy-woody-musty. Patchouli-like character. Key in earthy and patchouli accords."},
    {"name": "Costus Root Oil (Natural)", "cas": "8023-88-9", "odor_descriptors": ["earthy", "animalic", "musky", "hair", "warm"], "odor_families": ["earthy", "musky"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Saussurea costus. Animalic-earthy-hair. Very tenacious. Contains costol, dihydrocostunolide. IFRA: sensitization concerns."},

    # ========================================================================
    # ADDITIONAL NATURAL EXTRACTS (Essential Oils & Absolutes)
    # ========================================================================
    {"name": "Geranium Oil Bourbon (Natural)", "cas": "8000-46-2", "odor_descriptors": ["floral", "rosy", "minty", "green", "citrus"], "odor_families": ["floral", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FL/FR", "notes": "Pelargonium graveolens. Rose-minty-green. Contains citronellol, geraniol, linalool. Key in rose reconstructions and fougère."},
    {"name": "Ho Wood Oil (Natural)", "cas": "8022-91-5", "odor_descriptors": ["floral", "woody", "linalool", "camphor", "fresh"], "odor_families": ["floral", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Cinnamomum camphora. 97%+ linalool. Sustainable linalool source. Floral-woody-camphor."},
    {"name": "Rosewood Oil (Natural)", "cas": "8015-77-8", "odor_descriptors": ["floral", "woody", "linalool", "sweet", "spicy"], "odor_families": ["floral", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Aniba rosaeodora. 80%+ linalool. ENDANGERED. Sustainable ho wood oil is replacement. Sweet-floral-woody."},
    {"name": "Hyacinth Absolute (Natural)", "cas": "8015-21-4", "odor_descriptors": ["floral", "hyacinth", "green", "spicy", "rich"], "odor_families": ["floral", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Hyacinthus orientalis. Green-spicy-floral. Contains phenylacetaldehyde, benzyl alcohol, cinnamyl alcohol."},
    {"name": "Carnation Absolute (Natural)", "cas": "8023-86-3", "odor_descriptors": ["floral", "carnation", "spicy", "clove", "honey"], "odor_families": ["floral", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Dianthus caryophyllus. Spicy-clove-floral. Contains eugenol, iso-eugenol, benzyl benzoate."},
    {"name": "Jonquil Absolute (Natural)", "cas": "8024-05-3", "odor_descriptors": ["floral", "narcissus", "green", "hyacinth", "sweet"], "odor_families": ["floral", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Narcissus jonquilla. Green-floral-narcissus. Rare and expensive."},
    {"name": "Blackcurrant Bud Absolute (Natural)", "cas": "68991-50-4", "odor_descriptors": ["fruity", "catty", "green", "tropical", "sulfurous"], "odor_families": ["fruity", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Ribes nigrum. Catty-fruity-green with sulfur notes. Contains 4-mercapto-4-methylpentan-2-one. Key in cassis accords."},
    {"name": "Buchu Leaf Oil (Natural)", "cas": "8028-39-3", "odor_descriptors": ["herbal", "blackcurrant", "minty", "fruity", "sulfurous"], "odor_families": ["aromatic_herbal", "fruity"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Agathosma betulina. Blackcurrant-minty-herbal. Contains diosphenol, menthone. Key in cassis and fruity-herbal accords."},
    {"name": "Styrax Resinoid (Natural)", "cas": "8024-01-9", "odor_descriptors": ["balsamic", "sweet", "smoky", "warm", "leathery"], "odor_families": ["amber", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Liquidambar orientalis. Balsamic-sweet-smoky. Key in oriental, amber, and leather accords."},
    {"name": "Balsam Peru (Natural)", "cas": "8007-00-9", "odor_descriptors": ["balsamic", "vanilla", "cinnamon", "sweet", "warm"], "odor_families": ["amber", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Myroxylon balsamum. Vanilla-cinnamon-balsamic. Contains benzyl benzoate, cinnamic acid, vanillin. IFRA: restricted (sensitizer)."},
    {"name": "Benzoin Siam Resinoid (Natural)", "cas": "9000-72-0", "odor_descriptors": ["balsamic", "vanilla", "sweet", "warm", "rich"], "odor_families": ["amber", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Styrax tonkinensis. Richer and more vanilla than Sumatra benzoin. Sweet-balsamic-vanilla."},
    {"name": "Pine Needle Oil (Natural)", "cas": "8023-99-2", "odor_descriptors": ["fresh", "pine", "woody", "sharp", "coniferous"], "odor_families": ["aromatic_herbal", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Pinus sylvestris. Fresh-pine-woody. Contains alpha-pinene, delta-3-carene. Key in pine and conifer accords."},
    {"name": "Fir Balsam Oil (Natural)", "cas": "8021-27-0", "odor_descriptors": ["fresh", "pine", "sweet", "balsamic", "coniferous"], "odor_families": ["woody", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Abies balsamea. Sweet-balsamic-pine. Contains bornyl acetate, camphene. Holiday scent."},
    {"name": "Cypress Oil (Natural)", "cas": "8013-86-1", "odor_descriptors": ["fresh", "woody", "evergreen", "clean", "smoky"], "odor_families": ["woody", "aromatic_herbal"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Cupressus sempervirens. Fresh-evergreen-woody. Contains alpha-pinene, delta-3-carene."},
    {"name": "Elemi Resinoid (Natural)", "cas": "8023-89-0", "odor_descriptors": ["balsamic", "fresh", "lemony", "peppery", "incense"], "odor_families": ["amber", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Canarium luzonicum. Fresh-lemony-balsamic-peppery. Bridge between citrus and incense."},
    {"name": "Hay Absolute (Natural)", "cas": "N/A", "odor_descriptors": ["hay", "green", "sweet", "warm", "coumarinic"], "odor_families": ["green", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Dried grass/hay. Contains coumarin. Warm-sweet-green. Key in fougère and green-hay accords."},
    {"name": "Beeswax Absolute (Natural)", "cas": "8012-89-3", "odor_descriptors": ["honey", "wax", "warm", "sweet", "floral"], "odor_families": ["gourmand", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Apis mellifera wax. Honey-wax-warm. Very tenacious. Key in honey and warm-wax accords."},
    {"name": "Castoreum Absolute (Natural/Historical)", "cas": "8023-83-4", "odor_descriptors": ["animalic", "leather", "warm", "smoky", "ammoniacal"], "odor_families": ["musky", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Castor fiber. Animalic-leather-smoky. HISTORICAL: from beaver glands. Now synthetic. Key in chypre and leather accords."},
    {"name": "Civet Absolute (Natural/Historical)", "cas": "8039-20-5", "odor_descriptors": ["animalic", "fecal", "musk", "warm", "sweet"], "odor_families": ["musky"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Viverra civetta. Animalic-fecal-musk. HISTORICAL: from civet cat. Now synthetic. Contains civetone. Key in classic orientals and chypres."},
    {"name": "Ambergris (Natural/Historical)", "cas": "8038-63-7", "odor_descriptors": ["ambergris", "marine", "warm", "animalic", "tobacco"], "odor_families": ["amber", "musky"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Physeter macrocephalus. The original. From sperm whale digestion. Contains ambrein. ALL modern use is synthetic (Ambroxan, Ambroxide)."},

    # ========================================================================
    # KEY ESTERS & ACETALS
    # ========================================================================
    {"name": "Benzyl Salicylate", "cas": "118-58-1", "odor_descriptors": ["floral", "balsamic", "sweet", "warm", "subtle"], "odor_families": ["floral", "amber"], "formula": "C14H12O3", "mw": 228.24, "volatility": "base", "use": "FL/FR", "notes": "Balsamic-floral fixative. Very subtle odor. Used as a blender and fixative. Key in many classic fragrances."},
    {"name": "Benzyl Benzoate", "cas": "120-51-4", "odor_descriptors": ["balsamic", "sweet", "floral", "warm", "subtle"], "odor_families": ["amber", "floral"], "formula": "C14H12O2", "mw": 212.24, "volatility": "base", "use": "FL/FR", "notes": "Balsamic-sweet fixative. Very subtle. Most-used fixative in perfumery. Also a solvent."},
    {"name": "Benzyl Alcohol", "cas": "100-51-6", "odor_descriptors": ["floral", "jasmine", "sweet", "light", "fresh"], "odor_families": ["floral"], "formula": "C7H8O", "mw": 108.14, "volatility": "top", "use": "FL/FR", "notes": "Light jasmine-floral. Solvent and fixative. Found in jasmine and ylang-ylang."},
    {"name": "Ethyl Phenylacetate", "cas": "101-97-3", "odor_descriptors": ["floral", "honey", "sweet", "fruity", "warm"], "odor_families": ["floral", "gourmand"], "formula": "C10H12O2", "mw": 164.20, "volatility": "heart", "use": "FL/FR", "notes": "Honey-floral-fruity. Found in honey, passion fruit. Key in honey and fruity-floral accords."},
    {"name": "Phenyl Ethyl Acetate", "cas": "103-45-7", "odor_descriptors": ["floral", "rose", "fresh", "sweet", "fruity"], "odor_families": ["floral"], "formula": "C10H12O2", "mw": 164.20, "volatility": "top", "use": "FL/FR", "notes": "Fresh rose-fruity. The acetate of phenethyl alcohol. Lighter, fresher rose."},
    {"name": "Phenyl Ethyl Isobutyrate", "cas": "103-48-0", "odor_descriptors": ["floral", "rose", "fruity", "fresh", "sweet"], "odor_families": ["floral", "fruity"], "formula": "C12H16O2", "mw": 192.25, "volatility": "top", "use": "FL/FR", "notes": "Fruity-rose character. Fresh and sweet. Key in fruity-rose accords."},
    {"name": "Isobutyl Salicylate", "cas": "87-19-4", "odor_descriptors": ["floral", "orchid", "sweet", "spicy", "clean"], "odor_families": ["floral", "spicy"], "formula": "C11H14O3", "mw": 194.23, "volatility": "heart", "use": "FL/FR", "notes": "Orchid-sweet-spicy. Key in orchid and sweet-spicy floral accords."},
    {"name": "Methyl Salicylate", "cas": "119-36-8", "odor_descriptors": ["minty", "wintergreen", "sweet", "fresh", "medicinal"], "odor_families": ["aromatic_herbal", "green"], "formula": "C8H8O3", "mw": 152.15, "volatility": "top", "use": "FL/FR", "notes": "Wintergreen-minty. Found in wintergreen, birch bark. Key in root beer and wintergreen accords."},
    {"name": "Cinnamyl Alcohol", "cas": "104-54-1", "odor_descriptors": ["floral", "balsamic", "cinnamon", "sweet", "hyacinth"], "odor_families": ["spicy", "floral"], "formula": "C9H10O", "mw": 134.18, "volatility": "heart", "use": "FL/FR", "notes": "Hyacinth-balsamic-cinnamon. Softer than cinnamaldehyde. Key in hyacinth and balsamic-floral accords."},
    {"name": "Cinnamic Acid", "cas": "621-82-9", "odor_descriptors": ["balsamic", "sweet", "honey", "warm", "resinous"], "odor_families": ["amber", "gourmand"], "formula": "C9H8O2", "mw": 148.16, "volatility": "base", "use": "FL/FR", "notes": "Balsamic-honey fixative. Found in balsam of Peru, storax. Key in balsamic and honey accords."},
    {"name": "Amyl Cinnamic Aldehyde (ACA)", "cas": "122-40-7", "odor_descriptors": ["floral", "jasmine", "warm", "sweet", "fatty"], "odor_families": ["floral"], "formula": "C14H18O", "mw": 202.30, "volatility": "heart", "use": "FR", "notes": "Warm jasmine. The workhorse jasmine synthetic. IFRA: sensitizer, restricted. Key in jasmine and oriental accords."},
    {"name": "Hexyl Cinnamic Aldehyde (HCA)", "cas": "101-86-0", "odor_descriptors": ["floral", "jasmine", "warm", "fresh", "clean"], "odor_families": ["floral"], "formula": "C15H20O", "mw": 216.32, "volatility": "heart", "use": "FR", "notes": "Clean jasmine. IFRA-compliant alternative to ACA. Key in jasmine and clean-floral accords."},
    {"name": "Dihydrojasmone", "cas": "1128-08-1", "odor_descriptors": ["floral", "jasmine", "fresh", "green", "herbal"], "odor_families": ["floral", "green"], "formula": "C11H18O", "mw": 166.26, "volatility": "heart", "use": "FR", "notes": "Fresh jasmine-green. Simpler than cis-jasmone. Key in fresh jasmine accords."},
    {"name": "Methyl Dihydrojasmonate (Hedione)", "cas": "24851-98-7", "odor_descriptors": ["floral", "jasmine", "radiant", "diffusive", "fresh"], "odor_families": ["floral", "citrus"], "formula": "C13H22O3", "mw": 226.31, "volatility": "heart", "use": "FL/FR", "notes": "Revolutionary jasmine-radiance molecule. Used in virtually every modern fragrance. Not a true jasmine—more of an enhancer."},

    # ========================================================================
    # SULFUR / THIOL COMPOUNDS (Trace but Critical)
    # ========================================================================
    {"name": "4-Mercapto-4-Methylpentan-2-One", "cas": "19872-52-7", "odor_descriptors": ["catty", "blackcurrant", "tropical", "fruity", "sulfurous"], "odor_families": ["fruity", "green"], "formula": "C6H12OS", "mw": 132.22, "volatility": "top", "use": "FR", "notes": "THE cassis molecule. Extremely powerful—used at parts-per-billion. Found in Sauvignon blanc, blackcurrant. Key in cassis accords."},
    {"name": "Grapefruit Mercaptan", "cas": "71159-90-5", "odor_descriptors": ["grapefruit", "tropical", "sulfurous", "fresh", "citrus"], "odor_families": ["citrus", "fruity"], "formula": "C6H12OS", "mw": 132.22, "volatility": "top", "use": "FR", "notes": "THE grapefruit thiol. Extremely powerful. Found in grapefruit juice. Key in grapefruit and tropical accords."},
    {"name": "Thiogeraniol", "cas": "39067-81-5", "odor_descriptors": ["floral", "rose", "grapefruit", "sulfurous", "fresh"], "odor_families": ["floral", "citrus"], "formula": "C10H18S", "mw": 170.32, "volatility": "top", "use": "FR", "notes": "Rose-grapefruit with sulfurous nuance. Very powerful. Used at trace levels in rose and grapefruit accords."},

    # ========================================================================
    # ADDITIONAL KEY SYNTHETICS
    # ========================================================================
    {"name": "Koavone", "cas": "27710-82-3", "odor_descriptors": ["floral", "lavender", "herbal", "fresh", "fruity"], "odor_families": ["floral", "aromatic_herbal"], "formula": "C11H14O2", "mw": 178.23, "volatility": "heart", "use": "FR", "notes": "Lavender-fruity-floral. Key in fougère and floral-herbal accords."},
    {"name": "Dynascone 10", "cas": "56973-85-4", "odor_descriptors": ["green", "galbanum", "fresh", "fruity", "tropical"], "odor_families": ["green", "fruity"], "formula": "C11H18O", "mw": 166.26, "volatility": "top", "use": "FR", "notes": "Firmenich. Galbanum-green with fruity nuance. Modern galbanum alternative."},
    {"name": "Exaltone", "cas": "502-72-7", "odor_descriptors": ["musk", "warm", "animalic", "powdery", "elegant"], "odor_families": ["musky"], "formula": "C15H28O", "mw": 224.39, "volatility": "base", "use": "FR", "notes": "Macrocyclic musk ketone. Warm-animalic musk. More animalic than Exaltolide."},
    {"name": "Iso E Super", "cas": "5442-12-2", "odor_descriptors": ["woody", "cedar", "velvety", "amber", "musk", "clean"], "odor_families": ["woody", "amber", "musky"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "The molecule that launched molecular perfumery. Star of Molecule 01. Velvety woody-amber. Enhances other materials."},
    {"name": "Ambrocenide", "cas": "129326-82-7", "odor_descriptors": ["amber", "ambroxan", "rich", "warm", "powerful"], "odor_families": ["amber"], "formula": "C20H36O2", "mw": 308.50, "volatility": "base", "use": "FR", "notes": "Symrise. 10x more potent than Ambroxan. Extremely long-lasting ambergris."},
    {"name": "Mimosa Absolute (Natural)", "cas": "8022-98-6", "odor_descriptors": ["floral", "mimosa", "powdery", "green", "honey"], "odor_families": ["floral", "powdery"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Acacia dealbata. Powdery-green-honey floral. Key in floral bouquets and powdery accords."},
    {"name": "Ambrette Seed Absolute (Natural)", "cas": "8015-62-1", "odor_descriptors": ["musk", "floral", "warm", "fruity", "skin"], "odor_families": ["musky", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Hibiscus abelmoschus. The only natural plant musk. Contains ambrettolide. Very expensive."},
    {"name": "Kohinool", "cas": "N/A", "odor_descriptors": ["woody", "amber", "dry", "powdery"], "odor_families": ["woody", "amber"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "IFF. Dry woody-amber. Modern Norlimbanol alternative."},
    {"name": "Velivione", "cas": "N/A", "odor_descriptors": ["musk", "powdery", "velvety", "clean", "soft"], "odor_families": ["musky"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "Givaudan. Powdery-velvety musk. Soft, clean, elegant."},
    {"name": "Galaxolide (HHCB)", "cas": "1222-05-5", "odor_descriptors": ["musk", "clean", "sweet", "floral", "laundry", "powdery"], "odor_families": ["musky"], "formula": "C18H26O", "mw": 258.40, "volatility": "base", "use": "FR", "notes": "Most-used musk in perfumery. Clean laundry/skin musk. Environmental concerns (bioaccumulation)."},
    {"name": "Habanolide", "cas": "94201-28-6", "odor_descriptors": ["musk", "warm", "skin", "metallic", "clean"], "odor_families": ["musky"], "formula": "C16H28O2", "mw": 252.39, "volatility": "base", "use": "FR", "notes": "Warm skin musk with metallic edge. Macrocyclic. Warmer than Galaxolide."},
    {"name": "Cashmeran", "cas": "33704-61-9", "odor_descriptors": ["woody", "musk", "warm", "powdery", "cashmere"], "odor_families": ["woody", "musky"], "formula": "C14H26O", "mw": 210.36, "volatility": "base", "use": "FR", "notes": "The 'cashmere sweater' molecule. Woody-musky-powdery. Key in clean-laundry and soft-woody accords."},
    {"name": "Sandalore", "cas": "64430-87-5", "odor_descriptors": ["woody", "sandalwood", "musky", "warm"], "odor_families": ["woody", "musky"], "formula": "C12H22O", "mw": 182.30, "volatility": "base", "use": "FR", "notes": "Sandalwood-musk hybrid. Not as creamy as Ebanol but adds musky warmth."},
    {"name": "Polysantol", "cas": "107898-32-0", "odor_descriptors": ["woody", "sandalwood", "creamy", "sweet", "floral"], "odor_families": ["woody", "floral"], "formula": "C13H24O", "mw": 196.33, "volatility": "base", "use": "FR", "notes": "IFF. Creamy sandalwood with floral nuance. One of the best modern sandalwood synthetics."},
    {"name": "Calone", "cas": "60753-08-8", "odor_descriptors": ["marine", "melon", "watery", "ozone", "fresh"], "odor_families": ["aquatic"], "formula": "C10H10O3", "mw": 178.19, "volatility": "top", "use": "FR", "notes": "THE sea breeze molecule. Key to Cool Water (1988) and the entire aquatic family."},
    {"name": "Dihydromyrcenol", "cas": "18479-58-8", "odor_descriptors": ["fresh", "citrus", "lavender", "metallic", "clean"], "odor_families": ["aquatic", "citrus"], "formula": "C10H20O", "mw": 156.27, "volatility": "top", "use": "FR", "notes": "The Cool Water molecule. Fresh-citrus-lavender-metallic. Revolutionized masculine perfumery."},
    {"name": "Floralozone", "cas": "67634-15-5", "odor_descriptors": ["ozone", "fresh", "floral", "clean", "aquatic"], "odor_families": ["aquatic", "floral"], "formula": "C11H14O3", "mw": 194.23, "volatility": "top", "use": "FR", "notes": "Ozone-fresh-floral. Clean-aquatic-floral. Used in modern fresh fragrances."},
    {"name": "Evernyl (Veramoss)", "cas": "4707-47-5", "odor_descriptors": ["mossy", "woody", "earthy", "oakmoss", "fresh"], "odor_families": ["earthy", "woody"], "formula": "C10H12O4", "mw": 196.20, "volatility": "base", "use": "FR", "notes": "Synthetic oakmoss replacement. IFRA-compliant. Essential for modern chypre."},
    {"name": "Geosmin", "cas": "19700-21-1", "odor_descriptors": ["earthy", "petrichor", "soil", "damp", "fresh"], "odor_families": ["earthy"], "formula": "C12H22O", "mw": 182.30, "volatility": "top", "use": "FR", "notes": "The 'rain on dry earth' molecule. Used at parts-per-trillion. Key in earthy and mineral accords."},
    {"name": "Coumarin", "cas": "91-64-5", "odor_descriptors": ["sweet", "hay", "tonka", "almond", "warm"], "odor_families": ["gourmand", "green"], "formula": "C9H6O2", "mw": 146.14, "volatility": "heart", "use": "FL/FR", "notes": "Key in Fougère Royale (1882). Sweet-hay-tonka. IFRA restricted. Backbone of the fougère family."},
    {"name": "Vanillin", "cas": "121-33-5", "odor_descriptors": ["vanilla", "sweet", "gourmand", "creamy", "warm"], "odor_families": ["gourmand", "amber"], "formula": "C8H8O3", "mw": 152.15, "volatility": "base", "use": "FL/FR", "notes": "The most important gourmand molecule. Synthesized 1874. Key in oriental/ambery and gourmand families."},
]


def get_extended_molecules():
    """Return the extended seed molecule database."""
    return EXTENDED_MOLECULES
