"""
Comprehensive Seed Molecule Database
=====================================
Curated database of ~400+ commercially significant aroma molecules
covering all 15 odor families. This is the agent's backbone knowledge
that works without any scraping.

Each entry includes: name, CAS, odor descriptors, odor families,
molecular formula, molecular weight, volatility tier, key suppliers,
and usage notes.

Sources: TGSC, PubChem, Arctander (Perfume & Flavor Chemicals),
IFRA compliance data, industry catalogs.
"""

# Each molecule: {
#   name, cas, odor_descriptors, odor_families, formula, mw,
#   volatility (top/heart/base), use (FL/FR/both), notes
# }

SEED_MOLECULES = [
    # ========================================================================
    # FLORAL FAMILY
    # ========================================================================
    {"name": "Geraniol", "cas": "106-24-1", "odor_descriptors": ["floral", "rose", "geranium", "citronelly", "sweet"], "odor_families": ["floral", "citrus"], "formula": "C10H18O", "mw": 154.25, "volatility": "heart", "use": "FL/FR", "notes": "Primary rose note. Found in rose, geranium, citronella. IFRA: sensitizer, restricted to ~1% in leave-on."},
    {"name": "Citronellol", "cas": "106-22-9", "odor_descriptors": ["floral", "rose", "citronelly", "fresh", "lemony"], "odor_families": ["floral", "citrus"], "formula": "C10H20O", "mw": 156.27, "volatility": "heart", "use": "FL/FR", "notes": "Fresh rose with citrus facet. Key component of rose and geranium oils."},
    {"name": "Phenethyl Alcohol", "cas": "60-12-8", "odor_descriptors": ["floral", "rose", "honey", "sweet", "warm"], "odor_families": ["floral"], "formula": "C8H10O", "mw": 122.16, "volatility": "heart", "use": "FL/FR", "notes": "The 'rose petal' molecule. Major component of rose oil (60%+). Very versatile."},
    {"name": "Phenylacetaldehyde", "cas": "122-78-1", "odor_descriptors": ["floral", "hyacinth", "green", "honey", "sharp"], "odor_families": ["floral", "green"], "formula": "C8H8O", "mw": 120.15, "volatility": "top", "use": "FL/FR", "notes": "Hyacinth and narcissus character. Very powerful. Needs careful dosing."},
    {"name": "Hydroxycitronellal", "cas": "107-75-5", "odor_descriptors": ["floral", "lily", "muguet", "lily of the valley", "fresh", "sweet"], "odor_families": ["floral"], "formula": "C10H20O2", "mw": 172.27, "volatility": "heart", "use": "FR", "notes": "THE muguet/lily-of-the-valley molecule. IFRA: sensitizer, restricted. Replaced by Lilial (now also banned) and Lyral (also restricted). Bourgeonal and cyclamen aldehyde are current alternatives."},
    {"name": "Lilial (Butylphenyl Methylpropional)", "cas": "80-54-6", "odor_descriptors": ["floral", "lily", "muguet", "green", "fresh"], "odor_families": ["floral", "green"], "formula": "C14H20O", "mw": 204.31, "volatility": "heart", "use": "FR", "notes": "BANNED in EU/UK from March 2022 (CMR Cat 1B). Was the primary muguet replacement for hydroxycitronellal. Now replaced by Bourgeonal, cyclamen aldehyde, Florol."},
    {"name": "Lyral (Hydroxyisohexyl 3-Cyclohexene Carboxaldehyde)", "cas": "31906-04-4", "odor_descriptors": ["floral", "lily", "muguet", "fresh", "long-lasting"], "odor_families": ["floral"], "formula": "C14H24O2", "mw": 224.34, "volatility": "heart", "use": "FR", "notes": "Muguet/lily note. IFRA restricted (sensitizer). Less fresh than Lilial, more long-lasting."},
    {"name": "Bourgeonal", "cas": "18127-01-0", "odor_descriptors": ["floral", "lily", "muguet", "fresh", "green", "clean"], "odor_families": ["floral", "green"], "formula": "C13H18O", "mw": 190.28, "volatility": "heart", "use": "FR", "notes": "Lilial replacement. Fresh muguet with green facets. Used post-Lilial ban."},
    {"name": "Florol (Tetrahydro-2-isobutyl-4-methyl-4(2H)-pyranol)", "cas": "63500-88-9", "odor_descriptors": ["floral", "fresh", "natural", "lily", "muguet"], "odor_families": ["floral"], "formula": "C10H20O2", "mw": 172.27, "volatility": "heart", "use": "FL/FR", "notes": "Firmenich muguet alternative. Non-sensitizing. Natural-smelling floral."},
    {"name": "Cyclamen Aldehyde", "cas": "103-95-7", "odor_descriptors": ["floral", "cyclamen", "green", "fresh", "powdery"], "odor_families": ["floral", "green"], "formula": "C13H18O", "mw": 190.28, "volatility": "heart", "use": "FR", "notes": "Cyclamen flower note. Green-floral. Lilial alternative."},
    {"name": "Ionone Alpha", "cas": "127-41-3", "odor_descriptors": ["floral", "violet", "woody", "orris", "powdery"], "odor_families": ["floral", "powdery"], "formula": "C13H20O", "mw": 192.30, "volatility": "heart", "use": "FL/FR", "notes": "Classic violet note. Discovered 1893. Woody-floral fade."},
    {"name": "Ionone Beta", "cas": "14901-07-6", "odor_descriptors": ["floral", "violet", "raspberry", "woody", "fruity"], "odor_families": ["floral", "fruity"], "formula": "C13H20O", "mw": 192.30, "volatility": "heart", "use": "FL/FR", "notes": "More raspberry than alpha-ionone. The 'violet-raspberry' molecule."},
    {"name": "Methyl Ionone Gamma", "cas": "79-76-5", "odor_descriptors": ["floral", "violet", "orris", "powdery", "warm"], "odor_families": ["floral", "powdery"], "formula": "C14H22O", "mw": 206.33, "volatility": "heart", "use": "FR", "notes": "The finest of the ionones. Warm orris-violet. Essential in iris accords."},
    {"name": "Irone Alpha", "cas": "79-69-6", "odor_descriptors": ["floral", "iris", "orris", "violet", "powdery", "buttery"], "odor_families": ["floral", "powdery"], "formula": "C14H22O", "mw": 206.33, "volatility": "base", "use": "FR", "notes": "The genuine orris/iris molecule. Found naturally in orris butter. Extremely expensive. Synthetic alpha-irone is the key to orris reconstructions."},
    {"name": "Jasmine Absolute (Natural)", "cas": "8022-96-6", "odor_descriptors": ["floral", "jasmine", "indolic", "animalic", "sweet", "narcotic"], "odor_families": ["floral", "musky"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FL/FR", "notes": "Queen of florals. ~5000 flowers for 1g. Contains benzyl acetate, linalool, indole, cis-jasmone, methyl anthranilate."},
    {"name": "Cis-Jasmone", "cas": "488-49-3", "odor_descriptors": ["floral", "jasmine", "warm", "herbal", "fruity"], "odor_families": ["floral"], "formula": "C11H16O", "mw": 164.24, "volatility": "heart", "use": "FL/FR", "notes": "Key jasmine character. Natural-smelling jasmine with herbal undertones."},
    {"name": "Benzyl Acetate", "cas": "140-11-4", "odor_descriptors": ["floral", "jasmine", "fresh", "fruity", "light"], "odor_families": ["floral", "fruity"], "formula": "C9H10O2", "mw": 150.17, "volatility": "top", "use": "FL/FR", "notes": "Fresh jasmine top note. The most jasmine-like single chemical. Very common."},
    {"name": "Indole", "cas": "120-72-9", "odor_descriptors": ["floral", "jasmine", "animalic", "fecal", "narcotic"], "odor_families": ["floral", "musky"], "formula": "C8H7N", "mw": 117.15, "volatility": "heart", "use": "FL/FR", "notes": "The 'indolic' backbone of jasmine and orange blossom. Fecal in overdose, floral at trace. Essential for realistic jasmine."},
    {"name": "Hedione (Methyl Dihydrojasmonate)", "cas": "24851-98-7", "odor_descriptors": ["floral", "jasmine", "fresh", "radiant", "diffusive", "citrus"], "odor_families": ["floral", "citrus"], "formula": "C13H22O3", "mw": 226.31, "volatility": "heart", "use": "FL/FR", "notes": "Revolutionary. Introduced in Eau Sauvage (1966). Adds 'radiance' and diffusivity. Used in virtually every modern fragrance. Not a true jasmine—more of a 'jasmine impression' enhancer."},
    {"name": "Neroli Oil (Natural)", "cas": "8016-38-4", "odor_descriptors": ["floral", "orange blossom", "fresh", "citrus", "green", "light"], "odor_families": ["floral", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Steam-distilled orange blossom. Classic Eau de Cologne ingredient. Contains linalool, linalyl acetate, limonene."},
    {"name": "Methyl Anthranilate", "cas": "134-20-3", "odor_descriptors": ["floral", "orange blossom", "grape", "sweet", "neroli"], "odor_families": ["floral", "fruity"], "formula": "C8H9NO2", "mw": 151.16, "volatility": "heart", "use": "FL/FR", "notes": "Orange blossom and Concord grape character. Key in neroli accords. Reacts with aldehydes (Schiff base formation)."},
    {"name": "Tuberose Absolute (Natural)", "cas": "8024-05-3", "odor_descriptors": ["floral", "tuberose", "creamy", "narcotic", "indolic", "animalic"], "odor_families": ["floral", "musky"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Crepuscular, narcotic floral. Contains methyl salicylate, methyl anthranilate, eugenol. One of the most expensive naturals."},
    {"name": "Ylang Ylang Oil (Natural)", "cas": "8006-81-3", "odor_descriptors": ["floral", "ylang-ylang", "sweet", "banana", "narcotic", "spicy"], "odor_families": ["floral", "fruity"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FL/FR", "notes": "Cananga odorata. Sweet floral with banana facets. Extra grade is finest. Key in Chanel No. 5 and oriental blends."},
    {"name": "Eugenol", "cas": "97-53-0", "odor_descriptors": ["spicy", "clove", "warm", "carnation", "woody"], "odor_families": ["spicy", "floral"], "formula": "C10H12O2", "mw": 164.20, "volatility": "heart", "use": "FL/FR", "notes": "Clove and carnation character. IFRA restricted (sensitizer). Found in clove oil, cinnamon leaf, ylang-ylang."},
    {"name": "Iso Eugenol", "cas": "97-54-1", "odor_descriptors": ["floral", "carnation", "spicy", "clove", "sweet"], "odor_families": ["floral", "spicy"], "formula": "C10H12O2", "mw": 164.20, "volatility": "heart", "use": "FL/FR", "notes": "Smoother, more floral than eugenol. Key carnation material. IFRA restricted."},
    {"name": "Rose Oxide", "cas": "16409-43-1", "odor_descriptors": ["floral", "rose", "green", "geranium", "fresh", "metallic"], "odor_families": ["floral", "green"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FR", "notes": "The 'rose top note sparkle' molecule. Trace amounts in rose oil. Extremely powerful—used at <0.1%."},
    {"name": "Damascenone", "cas": "23726-93-4", "odor_descriptors": ["floral", "rose", "fruity", "plum", "tobacco", "honey"], "odor_families": ["floral", "fruity"], "formula": "C13H18O", "mw": 190.28, "volatility": "heart", "use": "FL/FR", "notes": "Key rose character. Plum-tobacco-rose. Found in rose oil and red fruits. Extremely potent."},
    {"name": "Damascone Beta", "cas": "23726-92-3", "odor_descriptors": ["floral", "rose", "plum", "blackcurrant", "tobacco"], "odor_families": ["floral", "fruity"], "formula": "C13H20O", "mw": 192.30, "volatility": "heart", "use": "FL/FR", "notes": "Rose with plum and cassis facets. More fruity than damascenone. Key in modern rose accords."},
    {"name": "Narcissus Absolute (Natural)", "cas": "8013-49-8", "odor_descriptors": ["floral", "narcissus", "green", "animalic", "hyacinth"], "odor_families": ["floral", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Green-floral with animalic depth. Rare and expensive. Contains benzyl acetate, methyl benzoate, indole."},
    {"name": "Gardenia Acetal (Methyl 2-Octynoate)", "cas": "111-12-6", "odor_descriptors": ["floral", "gardenia", "violet", "green", "fresh"], "odor_families": ["floral", "green"], "formula": "C9H14O2", "mw": 154.21, "volatility": "top", "use": "FL/FR", "notes": "Gardenia and violet leaf character. Very powerful. Used at trace levels."},

    # ========================================================================
    # CITRUS FAMILY
    # ========================================================================
    {"name": "Bergamot Oil FCF (Natural)", "cas": "8007-75-8", "odor_descriptors": ["citrus", "bergamot", "fresh", "fruity", "floral", "lavender"], "odor_families": ["citrus", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "The backbone of Eau de Cologne. FCF = furanocoumarin-free (required by IFRA for phototoxicity). Contains linalyl acetate (35%+), limonene, linalool."},
    {"name": "Limonene", "cas": "5989-27-5", "odor_descriptors": ["citrus", "orange", "fresh", "light", "sweet"], "odor_families": ["citrus"], "formula": "C10H16", "mw": 136.23, "volatility": "top", "use": "FL/FR", "notes": "The most common terpene. 90%+ of orange oil. Very short-lived. Weak odor but essential for 'juice' effect."},
    {"name": "Citral", "cas": "5392-40-5", "odor_descriptors": ["citrus", "lemon", "lemongrass", "fresh", "sharp"], "odor_families": ["citrus"], "formula": "C10H16O", "mw": 152.23, "volatility": "top", "use": "FL/FR", "notes": "Intense lemon. Mixture of neral and geranial. IFRA: sensitizer. Key in lemon reconstructions."},
    {"name": "Linalool", "cas": "78-70-6", "odor_descriptors": ["floral", "lavender", "bergamot", "fresh", "citrus", "sweet"], "odor_families": ["floral", "citrus"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Universal building block. Found in 200+ essential oils. Fresh floral-citrus. IFRA: sensitizer but widely used. Key in lavender, bergamot, rose accords."},
    {"name": "Linalyl Acetate", "cas": "115-95-7", "odor_descriptors": ["citrus", "bergamot", "floral", "fresh", "lavender", "sweet"], "odor_families": ["citrus", "floral"], "formula": "C12H20O2", "mw": 196.29, "volatility": "top", "use": "FL/FR", "notes": "Bergamot and lavender character. Main component of bergamot oil (35%+). Smoother than linalool."},
    {"name": "Nootkatone", "cas": "4674-50-4", "odor_descriptors": ["citrus", "grapefruit", "bitter", "fresh", "woody"], "odor_families": ["citrus", "woody"], "formula": "C15H22O", "mw": 218.33, "volatility": "heart", "use": "FL/FR", "notes": "The signature grapefruit molecule. Very expensive natural; bio-synthesized versions available. Woody-grapefruit."},
    {"name": "Petitgrain Oil Paraguay (Natural)", "cas": "8014-17-3", "odor_descriptors": ["citrus", "orange leaf", "fresh", "woody", "floral"], "odor_families": ["citrus", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Bitter orange leaf distillation. Fresh citrus-woody. Key in cologne and fougère accords."},
    {"name": "Decanal (Aldehyde C-10)", "cas": "112-31-2", "odor_descriptors": ["citrus", "orange peel", "waxy", "floral", "fresh"], "odor_families": ["citrus", "aldehydic"], "formula": "C10H20O", "mw": 156.27, "volatility": "top", "use": "FL/FR", "notes": "Orange peel character. Key aldehyde in Chanel No. 5. Use at trace for sparkle."},
    {"name": "Dodecanal (Aldehyde C-12 MNA)", "cas": "112-54-9", "odor_descriptors": ["aldehydic", "soapy", "waxy", "metallic", "fatty", "clean"], "odor_families": ["aldehydic", "citrus"], "formula": "C12H24O", "mw": 184.32, "volatility": "top", "use": "FL/FR", "notes": "THE Chanel No. 5 aldehyde. Soapy, metallic, fatty. Use at <1% for 'champagne fizz'."},
    {"name": "Undecanal (Aldehyde C-11)", "cas": "112-44-7", "odor_descriptors": ["aldehydic", "waxy", "floral", "fresh", "soapy"], "odor_families": ["aldehydic"], "formula": "C11H22O", "mw": 170.29, "volatility": "top", "use": "FR", "notes": "Floral-aldehydic. 'Rose-aldehyde' character. Important in aldehydic florals."},
    {"name": "Nonanal (Aldehyde C-9)", "cas": "124-19-6", "odor_descriptors": ["aldehydic", "floral", "rose", "citrus", "waxy", "fatty"], "odor_families": ["aldehydic", "floral"], "formula": "C9H18O", "mw": 142.24, "volatility": "top", "use": "FL/FR", "notes": "Rose-citrus aldehyde. Natural component of rose and citrus oils."},

    # ========================================================================
    # WOODY FAMILY
    # ========================================================================
    {"name": "Iso E Super (Tetramethyl Octahydronaphthalenfuran)", "cas": "5442-12-2", "odor_descriptors": ["woody", "cedar", "velvety", "amber", "musk", "clean"], "odor_families": ["woody", "amber", "musky"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "The molecule that launched molecular perfumery. Star of Molecule 01. Velvety woody-amber. Enhances other materials. Can be used at 50%+ of formula."},
    {"name": "Ambroxan (Ambroxide)", "cas": "6790-58-5", "odor_descriptors": ["ambergris", "warm", "woody", "mineral", "sweet", "animalic"], "odor_families": ["amber", "woody"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "Synthetic ambergris. Key in Sauvage, Baccarat Rouge 540. Very long-lasting. Warm-woody-ambergris. Can be used as a near-solo ingredient (Not A Perfume, JHAG)."},
    {"name": "Norlimbanol (Timberol)", "cas": "70788-30-6", "odor_descriptors": ["woody", "amber", "dry", "dusty", "warm"], "odor_families": ["woody", "amber"], "formula": "C13H24O", "mw": 196.33, "volatility": "base", "use": "FR", "notes": "The 'dry wood' molecule. Key in Dior Sauvage and modern masculines. Amber-woody-dry. Very tenacious."},
    {"name": "Sandalwood Oil Indian (Natural)", "cas": "8006-87-9", "odor_descriptors": ["woody", "sandalwood", "creamy", "smooth", "meditative", "sweet"], "odor_families": ["woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Santalum album. The finest sandalwood. Endangered/overharvested. Contains alpha-santalol (50%+) and beta-santalol. Australian (S. spicatum) is sustainable alternative with different profile."},
    {"name": "Ebanol", "cas": "91481-32-0", "odor_descriptors": ["woody", "sandalwood", "creamy", "sweet", "warm"], "odor_families": ["woody"], "formula": "C13H22O", "mw": 194.31, "volatility": "base", "use": "FR", "notes": "Synthetic sandalwood. Creamy, sweet, woody. Stronger than sandela. Good sandalwood reconstruction ingredient."},
    {"name": "Javanol", "cas": "1205-09-0", "odor_descriptors": ["woody", "sandalwood", "creamy", "rich", "warm"], "odor_families": ["woody"], "formula": "C11H22O", "mw": 170.29, "volatility": "base", "use": "FR", "notes": "Firmenich. The most potent synthetic sandalwood. 5-10x stronger than Ebanol. Creamy-sweet-woody."},
    {"name": "Patchouli Oil (Natural)", "cas": "8000-27-9", "odor_descriptors": ["woody", "earthy", "camphoraceous", "sweet", "spicy", "musty"], "odor_families": ["woody", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Essential to chypre and oriental families. Contains patchoulol (27-35%). Heart (distilled) version is smoother. Indonesian is standard; premium grades from Sulawesi."},
    {"name": "Vetiver Oil Haitian (Natural)", "cas": "8016-96-4", "odor_descriptors": ["woody", "earthy", "smoky", "grapefruit", "rooty", "green"], "odor_families": ["woody", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Haitian is smoother, more grapefruit. Java is smokier. Bourbon (Réunion) is finest. Contains vetiverol, vetivone. Essential in masculine and chypre."},
    {"name": "Vetiveryl Acetate", "cas": "62563-80-8", "odor_descriptors": ["woody", "vetiver", "smooth", "elegant", "grapefruit", "clean"], "odor_families": ["woody"], "formula": "N/A (derivative)", "mw": None, "volatility": "base", "use": "FR", "notes": "Acetylated vetiver. Smoother and more elegant than vetiver oil. Less earthy, more refined woody-grapefruit."},
    {"name": "Cedarwood Atlas Oil (Natural)", "cas": "8000-27-9", "odor_descriptors": ["woody", "cedar", "warm", "balsamic", "camphoraceous"], "odor_families": ["woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Cedrus atlantica. Warm, balsamic cedar. Contains alpha-cedrene, cedrol. Warmer than Virginia cedar."},
    {"name": "Cedrol", "cas": "77-53-2", "odor_descriptors": ["woody", "cedar", "dry", "warm", "sweet"], "odor_families": ["woody"], "formula": "C15H26O", "mw": 222.37, "volatility": "base", "use": "FR", "notes": "Cedar alcohol. Dry, warm cedar character. Fixative."},
    {"name": "Oud Oil (Agarwood, Natural)", "cas": "N/A", "odor_descriptors": ["woody", "smoky", "animalic", "sweet", "balsamic", "complex"], "odor_families": ["woody", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Most expensive raw material in perfumery. Aquilaria species. Wild harvest unsustainable; plantation oud emerging. Contains agarospirol, jinkoh-eremol. Key in Middle Eastern attar tradition."},
    {"name": "Cashmeran", "cas": "33704-61-9", "odor_descriptors": ["woody", "musk", "warm", "powdery", "cashmere", "smooth"], "odor_families": ["woody", "musky"], "formula": "C14H26O", "mw": 210.36, "volatility": "base", "use": "FR", "notes": "The 'cashmere sweater' molecule. Woody-musky-powdery. Used in clean-laundry and soft-woody accords. Key in detergent perfumery too."},
    {"name": "Sandalore", "cas": "64430-87-5", "odor_descriptors": ["woody", "sandalwood", "musky", "warm", "smooth"], "odor_families": ["woody", "musky"], "formula": "C12H22O", "mw": 182.30, "volatility": "base", "use": "FR", "notes": "Sandalwood-musk hybrid. Not as creamy as Ebanol or Javanol but adds musky warmth."},
    {"name": "Polysantol", "cas": "107898-32-0", "odor_descriptors": ["woody", "sandalwood", "creamy", "sweet", "floral"], "odor_families": ["woody", "floral"], "formula": "C13H24O", "mw": 196.33, "volatility": "base", "use": "FR", "notes": "IFF. Creamy sandalwood with floral nuance. One of the best modern sandalwood synthetics."},

    # ========================================================================
    # AMBER FAMILY
    # ========================================================================
    {"name": "Labdanum Absolute (Natural)", "cas": "8016-26-0", "odor_descriptors": ["amber", "labdanum", "resinous", "leathery", "warm", "balsamic"], "odor_families": ["amber", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Cistus ladanifer. The backbone of amber accords. Contains labdane diterpenes, ambrarome. Provides the 'warm amber' foundation."},
    {"name": "Ambrarome (Ambrein Degradation Product)", "cas": "N/A", "odor_descriptors": ["amber", "warm", "animalic", "tobacco", "leathery", "rich"], "odor_families": ["amber", "leathery"], "formula": "N/A (mixture)", "mw": None, "volatility": "base", "use": "FR", "notes": "Thermal degradation product of ambergris/ambrein. Rich, warm amber-tobacco. Key in classic amber accords."},
    {"name": "Vanillin", "cas": "121-33-5", "odor_descriptors": ["vanilla", "sweet", "gourmand", "creamy", "warm"], "odor_families": ["gourmand", "amber"], "formula": "C8H8O3", "mw": 152.15, "volatility": "base", "use": "FL/FR", "notes": "Synthesized 1874. The most important gourmand molecule. Key in oriental/ambery and gourmand families. Found naturally in vanilla beans (1-3%)."},
    {"name": "Ethyl Vanillin", "cas": "121-32-4", "odor_descriptors": ["vanilla", "sweet", "gourmand", "creamy", "intense"], "odor_families": ["gourmand", "amber"], "formula": "C9H10O3", "mw": 166.17, "volatility": "base", "use": "FL/FR", "notes": "2-3x stronger than vanillin. Sweeter, more intense. Used when vanillin isn't sweet enough."},
    {"name": "Benzoin Resinoid (Natural)", "cas": "9000-72-0", "odor_descriptors": ["balsamic", "vanilla", "sweet", "warm", "amber", "resinous"], "odor_families": ["amber", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Styrax benzoin or tonkinensis. Sweet balsamic-vanilla. Key in oriental and amber accords. Contains benzoic acid, vanillin, coniferyl benzoate."},
    {"name": "Tolu Balsam (Natural)", "cas": "9000-64-0", "odor_descriptors": ["balsamic", "vanilla", "cinnamon", "warm", "sweet"], "odor_families": ["amber", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Myroxylon balsamum. Cinnamon-vanilla-balsamic. Used in oriental and amber accords."},
    {"name": "Myrrh Resinoid (Natural)", "cas": "8016-37-3", "odor_descriptors": ["balsamic", "resinous", "warm", "incense", "medicinal", "earthy"], "odor_families": ["amber", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Commiphora myrrha. Warm, balsamic, slightly medicinal. Used in incense and oriental accords."},
    {"name": "Frankincense Oil (Natural)", "cas": "8016-36-2", "odor_descriptors": ["resinous", "lemony", "smoky", "incense", "woody", "fresh"], "odor_families": ["amber", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Boswellia species. Lemony-pine-resinous top note. Used in meditation and religious ceremony for millennia."},
    {"name": "Ambrettolide", "cas": "28645-51-4", "odor_descriptors": ["musk", "amber", "warm", "floral", "fruity", "skin"], "odor_families": ["musky", "amber"], "formula": "C16H28O2", "mw": 252.39, "volatility": "base", "use": "FR", "notes": "Natural musk from ambrette seed. Macrocyclic musk. Fruity-floral-musk. One of the few 'natural' musks. Very expensive; synthetic version widely used."},

    # ========================================================================
    # MUSKY FAMILY
    # ========================================================================
    {"name": "Galaxolide (HHCB)", "cas": "1222-05-5", "odor_descriptors": ["musk", "clean", "sweet", "floral", "laundry", "powdery"], "odor_families": ["musky"], "formula": "C18H26O", "mw": 258.40, "volatility": "base", "use": "FR", "notes": "Most-used musk in perfumery. Clean laundry/skin musk. Polycyclic. Environmental concerns (bioaccumulation). Used in everything from fine fragrance to detergent."},
    {"name": "Habanolide", "cas": "94201-28-6", "odor_descriptors": ["musk", "warm", "skin", "metallic", "clean", "animalic"], "odor_families": ["musky"], "formula": "C16H28O2", "mw": 252.39, "volatility": "base", "use": "FR", "notes": "Warm skin musk with metallic edge. Macrocyclic (more biodegradable than polycyclic). Warmer than Galaxolide. Used in modern 'skin scent' compositions."},
    {"name": "Ethylene Brassylate", "cas": "105-96-4", "odor_descriptors": ["musk", "clean", "soapy", "sweet", "powdery"], "odor_families": ["musky"], "formula": "C15H26O4", "mw": 270.36, "volatility": "base", "use": "FR", "notes": "Macrocylic musk. Clean-powdery. Good fixative. Often used as the musk backbone in masculine fragrances."},
    {"name": "Exaltolide", "cas": "106-02-5", "odor_descriptors": ["musk", "clean", "warm", "powdery", "elegant", "animalic"], "odor_families": ["musky"], "formula": "C15H28O2", "mw": 240.38, "volatility": "base", "use": "FR", "notes": "Pentadecanolide. The classic macrocyclic musk. Elegant, warm. Natural musk-like. More expensive than Galaxolide but higher quality."},
    {"name": "Musk T (2,4,6-Trinitro-1,3-dimethyl-tert-butylbenzene)", "cas": "81-15-2", "odor_descriptors": ["musk", "warm", "animalic", "powdery", "sweet"], "odor_families": ["musky"], "formula": "C12H15N3O6", "mw": 297.27, "volatility": "base", "use": "FR", "notes": "HISTORICAL. Nitro musk. Now banned/restricted due to environmental persistence. Replaced by polycyclic and macrocyclic musks."},
    {"name": "Serenolide", "cas": "141776-68-7", "odor_descriptors": ["musk", "clean", "fresh", "floral", "light"], "odor_families": ["musky"], "formula": "C14H24O3", "mw": 240.34, "volatility": "base", "use": "FR", "notes": "IFF. Light, clean musk with floral undertones. Good for fresh-clean compositions."},
    {"name": "Sylkolide", "cas": "141712-42-3", "odor_descriptors": ["musk", "clean", "powdery", "soft", "skin"], "odor_families": ["musky"], "formula": "C15H28O2", "mw": 240.38, "volatility": "base", "use": "FR", "notes": "Symrise. Soft skin musk. Clean, powdery. Good alternative to Galaxolide with better biodegradability."},

    # ========================================================================
    # SPICY FAMILY
    # ========================================================================
    {"name": "Cinnamaldehyde", "cas": "104-55-2", "odor_descriptors": ["spicy", "cinnamon", "warm", "sweet", "balsamic"], "odor_families": ["spicy", "amber"], "formula": "C9H8O", "mw": 132.16, "volatility": "top", "use": "FL/FR", "notes": "Cinnamon character. IFRA restricted (sensitizer). Very powerful. Key in oriental and gourmand accords."},
    {"name": "Cinnamyl Alcohol", "cas": "104-54-1", "odor_descriptors": ["floral", "balsamic", "cinnamon", "sweet", "hyacinth"], "odor_families": ["spicy", "floral"], "formula": "C9H10O", "mw": 134.18, "volatility": "heart", "use": "FL/FR", "notes": "Softer, more floral than cinnamaldehyde. Hyacinth and balsamic character."},
    {"name": "Cardamom Oil (Natural)", "cas": "8000-66-6", "odor_descriptors": ["spicy", "cardamom", "eucalyptus", "fresh", "warm", "camphoraceous"], "odor_families": ["spicy", "aromatic_herbal"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Elettaria cardamomum. Fresh spicy-eucalyptus. Contains 1,8-cineole, alpha-terpinyl acetate. Key in oriental and fougère."},
    {"name": "Black Pepper Oil (Natural)", "cas": "8006-82-4", "odor_descriptors": ["spicy", "pepper", "warm", "woody", "sharp"], "odor_families": ["spicy", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Piper nigrum. Warm, sharp, woody-spicy. Contains beta-caryophyllene, limonene. Key in modern masculine fragrances."},
    {"name": "Ginger Oil (Natural)", "cas": "8007-08-7", "odor_descriptors": ["spicy", "ginger", "fresh", "warm", "citrus", "woody"], "odor_families": ["spicy", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Zingiber officinale. Fresh-spicy with citrus-woody facets. Contains zingiberene, curcumene."},
    {"name": "Saffron", "cas": "N/A", "odor_descriptors": ["spicy", "saffron", "warm", "leathery", "hay", "honey"], "odor_families": ["spicy", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Crocus sativus. The world's most expensive spice. Contains safranal, crocin. Warm-spicy-hay-leathery. Key in oud-rose-saffron orientals."},

    # ========================================================================
    # GREEN FAMILY
    # ========================================================================
    {"name": "Galbanum Oil (Natural)", "cas": "8023-86-3", "odor_descriptors": ["green", "bitter", "earthy", "fresh", "sharp", "vegetable"], "odor_families": ["green", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Ferula galbaniflua. THE green material. Bitter-green, sharp. Contains alpha-pinene, beta-pinene. Key in Vent Vert and green florals."},
    {"name": "Leaf Alcohol (cis-3-Hexenol)", "cas": "928-96-1", "odor_descriptors": ["green", "grass", "fresh", "leaf", "cut grass", "sharp"], "odor_families": ["green"], "formula": "C6H12O", "mw": 100.16, "volatility": "top", "use": "FL/FR", "notes": "The 'freshly cut grass' molecule. Found in green leaves. Very powerful. Essential for green accords."},
    {"name": "Stemone", "cas": "33704-76-0", "odor_descriptors": ["green", "stemmy", "tomato leaf", "fig leaf", "fresh"], "odor_families": ["green"], "formula": "C9H17NO", "mw": 155.24, "volatility": "top", "use": "FR", "notes": "Fig leaf and tomato stem character. Key in modern green-fig compositions."},
    {"name": "Violet Leaf Absolute (Natural)", "cas": "8024-08-6", "odor_descriptors": ["green", "violet leaf", "cucumber", "fresh", "peppery"], "odor_families": ["green", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Viola odorata. Green-cucumber-peppery. Contains 2,6-nonadienal (cucumber aldehyde). Expensive but irreplaceable."},
    {"name": "Mintonat", "cas": "N/A", "odor_descriptors": ["green", "mint", "fresh", "cool", "aromatic"], "odor_families": ["green", "aromatic_herbal"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Fresh green-mint character. Used in green and aromatic compositions."},

    # ========================================================================
    # FRUITY FAMILY
    # ========================================================================
    {"name": "Ethyl Maltol", "cas": "4940-11-8", "odor_descriptors": ["cotton candy", "caramel", "strawberry", "sweet", "fruity"], "odor_families": ["gourmand", "fruity"], "formula": "C7H8O3", "mw": 140.14, "volatility": "heart", "use": "FL/FR", "notes": "3-5x sweeter than maltol. THE gourmand molecule. Pioneered by Angel (1992). Cotton candy-strawberry-caramel. Extremely sweet."},
    {"name": "Maltol", "cas": "118-71-8", "odor_descriptors": ["caramel", "cotton candy", "sweet", "fruity", "jammy"], "odor_families": ["gourmand", "fruity"], "formula": "C6H6O3", "mw": 126.11, "volatility": "heart", "use": "FL/FR", "notes": "Natural caramel note. Found in strawberry, mango, roasted coffee. Less sweet than ethyl maltol but more natural-smelling."},
    {"name": "Gamma-Undecalactone (Aldehyde C-14)", "cas": "104-67-6", "odor_descriptors": ["peach", "creamy", "fruity", "lactonic", "sweet"], "odor_families": ["fruity", "gourmand"], "formula": "C11H20O2", "mw": 184.28, "volatility": "heart", "use": "FL/FR", "notes": "THE peach molecule. Despite 'aldehyde' name, it's a lactone. Creamy-fruity-peach. Key in peach, apricot, and fruity-floral accords."},
    {"name": "Gamma-Nonalactone (Aldehyde C-18)", "cas": "104-61-0", "odor_descriptors": ["coconut", "creamy", "sweet", "fruity", "lactonic"], "odor_families": ["fruity", "gourmand"], "formula": "C9H16O2", "mw": 156.22, "volatility": "heart", "use": "FL/FR", "notes": "THE coconut molecule. Creamy-sweet-coconut. Used in suntan-lotion and tropical accords."},
    {"name": "Furaneol (Strawberry Furanone)", "cas": "3658-77-3", "odor_descriptors": ["strawberry", "fruity", "sweet", "caramel", "tropical"], "odor_families": ["fruity", "gourmand"], "formula": "C6H8O3", "mw": 128.13, "volatility": "heart", "use": "FL/FR", "notes": "Strawberry-tropical character. Found in strawberries, mangoes, pineapple. Key in fruity and tropical accords."},
    {"name": "Fructone (Ethyl Acetoacetate Ethylene Glycol Ketal)", "cas": "6413-10-1", "odor_descriptors": ["fruity", "apple", "fresh", "sweet"], "odor_families": ["fruity"], "formula": "C8H14O4", "mw": 174.19, "volatility": "top", "use": "FL/FR", "notes": "Fresh apple-fruity. Light, clean fruity character."},
    {"name": "Allyl Amyl Glycolate", "cas": "67634-00-8", "odor_descriptors": ["fruity", "pineapple", "green", "fresh", "tropical"], "odor_families": ["fruity", "green"], "formula": "C10H18O3", "mw": 186.25, "volatility": "top", "use": "FR", "notes": "Pineapple-green character. Very diffusive. Used in tropical and fruity accords."},

    # ========================================================================
    # GOURMAND FAMILY
    # ========================================================================
    {"name": "Tonka Bean Absolute (Natural)", "cas": "8024-06-4", "odor_descriptors": ["coumarinic", "sweet", "almond", "vanilla", "tobacco", "hay"], "odor_families": ["gourmand", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Dipteryx odorata. Contains coumarin (30-50%). Sweet-hay-almond-vanilla. Key in fougère and oriental. IFRA: coumarin restricted."},
    {"name": "Coumarin", "cas": "91-64-5", "odor_descriptors": ["sweet", "hay", "tonka", "almond", "warm", "green"], "odor_families": ["gourmand", "green"], "formula": "C9H6O2", "mw": 146.14, "volatility": "heart", "use": "FL/FR", "notes": "Synthesized 1868. Key in Fougère Royale (1882). Sweet-hay-tonka. IFRA restricted. Backbone of the fougère family."},
    {"name": "Dihydrocoumarin", "cas": "119-84-6", "odor_descriptors": ["sweet", "tonka", "hay", "coconut", "warm"], "odor_families": ["gourmand"], "formula": "C9H8O2", "mw": 148.16, "volatility": "heart", "use": "FL/FR", "notes": "Smoother, more coconut-like than coumarin. Tonka-coconut sweetness."},
    {"name": "Cocoa Absolute (Natural)", "cas": "84649-99-0", "odor_descriptors": ["chocolate", "cocoa", "rich", "bitter", "sweet", "warm"], "odor_families": ["gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Theobroma cacao. Rich bitter chocolate. Used in gourmand accords. Very tenacious."},
    {"name": "Coffee Absolute (Natural)", "cas": "8001-67-0", "odor_descriptors": ["coffee", "roasted", "bitter", "warm", "rich"], "odor_families": ["gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FL/FR", "notes": "Coffea arabica. Rich, roasted, bitter. Used in gourmand and oriental accords."},

    # ========================================================================
    # AQUATIC FAMILY
    # ========================================================================
    {"name": "Calone (Methylbenzodioxepinone)", "cas": "60753-08-8", "odor_descriptors": ["marine", "melon", "watery", "ozone", "fresh", "sea breeze"], "odor_families": ["aquatic"], "formula": "C10H10O3", "mw": 178.19, "volatility": "top", "use": "FR", "notes": "THE sea breeze molecule. Invented 1966, popularized 1990s. Key to Cool Water (1988) and the entire aquatic family. Very powerful."},
    {"name": "Dihydromyrcenol", "cas": "18479-58-8", "odor_descriptors": ["fresh", "citrus", "lavender", "metallic", "soapy", "clean"], "odor_families": ["aquatic", "citrus"], "formula": "C10H20O", "mw": 156.27, "volatility": "top", "use": "FR", "notes": "The Cool Water molecule. Fresh-citrus-lavender-metallic. Revolutionized masculine perfumery (1988). Key in aquatic and fresh fragrances."},
    {"name": "Floralozone", "cas": "67634-15-5", "odor_descriptors": ["ozone", "fresh", "floral", "clean", "aquatic", "powdery"], "odor_families": ["aquatic", "floral"], "formula": "C11H14O3", "mw": 194.23, "volatility": "top", "use": "FR", "notes": "Ozone-fresh character. Clean-aquatic-floral. Used in modern fresh fragrances."},
    {"name": "Azurone", "cas": "N/A", "odor_descriptors": ["marine", "watery", "fresh", "clean", "ozone"], "odor_families": ["aquatic"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Givaudan. Marine-watery-ozone. Modern aquatic molecule."},

    # ========================================================================
    # AROMATIC / HERBAL FAMILY
    # ========================================================================
    {"name": "Lavender Oil (Natural)", "cas": "8000-28-0", "odor_descriptors": ["lavender", "fresh", "herbal", "floral", "camphoraceous", "clean"], "odor_families": ["aromatic_herbal", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Lavandula angustifolia. THE fougère ingredient. Contains linalool (35%+), linalyl acetate (25%+). Top note of the masculine fragrance tradition."},
    {"name": "Rosemary Oil (Natural)", "cas": "8000-25-9", "odor_descriptors": ["herbal", "rosemary", "fresh", "camphoraceous", "woody", "green"], "odor_families": ["aromatic_herbal", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Contains 1,8-cineole, camphor, alpha-pinene. Key in Eau de Cologne and fougère."},
    {"name": "Thyme Oil (Natural)", "cas": "8007-46-3", "odor_descriptors": ["herbal", "thyme", "warm", "spicy", "fresh"], "odor_families": ["aromatic_herbal", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Thymus vulgaris. Contains thymol. Warm-herbal-spicy."},
    {"name": "Eucalyptus Oil (Natural)", "cas": "8000-48-4", "odor_descriptors": ["camphoraceous", "eucalyptus", "fresh", "medicinal", "cool"], "odor_families": ["aromatic_herbal"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Contains 1,8-cineole (80%+). Fresh-medicinal-cool. Used in respiratory and fresh accords."},
    {"name": "1,8-Cineole (Eucalyptol)", "cas": "470-82-6", "odor_descriptors": ["camphoraceous", "eucalyptus", "fresh", "cool", "medicinal"], "odor_families": ["aromatic_herbal"], "formula": "C10H18O", "mw": 154.25, "volatility": "top", "use": "FL/FR", "notes": "Fresh-camphoraceous. Found in eucalyptus, rosemary, cardamom. The 'cool breath' molecule."},
    {"name": "Clary Sage Oil (Natural)", "cas": "8016-63-5", "odor_descriptors": ["herbal", "amber", "warm", "tea", "tobacco", "fresh"], "odor_families": ["aromatic_herbal", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Contains linalyl acetate, sclareol. Herbal-amber-tea. Source of sclareol for Ambroxan synthesis."},

    # ========================================================================
    # POWDERY FAMILY
    # ========================================================================
    {"name": "Orris Concrete/Butter (Natural)", "cas": "8002-73-1", "odor_descriptors": ["orris", "iris", "powdery", "violet", "buttery", "woody"], "odor_families": ["powdery", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Iris pallida rhizomes. Must age 3-5 years. Contains alpha-irone. The most expensive raw material per gram. Buttery-powdery-woody-violet."},
    {"name": "Heliotropin (Piperonal)", "cas": "120-57-0", "odor_descriptors": ["powdery", "heliotrope", "cherry", "vanilla", "sweet", "floral"], "odor_families": ["powdery", "floral"], "formula": "C8H6O3", "mw": 150.13, "volatility": "heart", "use": "FL/FR", "notes": "Heliotrope and cherry-almond character. Sweet-powdery-floral. Key in powdery and oriental accords."},
    {"name": "Acetophenone", "cas": "98-86-2", "odor_descriptors": ["sweet", "floral", "hawthorn", "orange blossom", "powdery"], "odor_families": ["powdery", "floral"], "formula": "C8H8O", "mw": 120.15, "volatility": "heart", "use": "FL/FR", "notes": "Hawthorn and orange blossom character. Sweet-floral-powdery."},

    # ========================================================================
    # LEATHERY FAMILY
    # ========================================================================
    {"name": "Isobutyl Quinoline (IBQ)", "cas": "93-19-6", "odor_descriptors": ["leather", "earthy", "nutty", "smoky", "green", "bitter"], "odor_families": ["leathery", "earthy"], "formula": "C13H15N", "mw": 185.27, "volatility": "heart", "use": "FR", "notes": "THE leather molecule. Earthy-leather-nutty. Key in Cuir de Russie, Knize Ten. Very powerful and tenacious."},
    {"name": "Birch Tar Oil (Natural)", "cas": "8001-88-5", "odor_descriptors": ["smoky", "leather", "woody", "tar", "burnt", "wintergreen"], "odor_families": ["leathery", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Betula alba. Smoky-leather-tar. Traditional Russian leather perfume ingredient. Contains betulin, guaiacol. IFRA: restricted (polycyclic aromatics)."},
    {"name": "Safraleine", "cas": "N/A", "odor_descriptors": ["leather", "saffron", "spicy", "tobacco", "warm"], "odor_families": ["leathery", "spicy"], "formula": "N/A (proprietary)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Givaudan. Leather-saffron hybrid. Warm-spicy-leather. Key in modern leather accords."},
    {"name": "Cuir Absolute (Natural/Lab)", "cas": "N/A", "odor_descriptors": ["leather", "suede", "warm", "animalic", "smoky"], "odor_families": ["leathery"], "formula": "N/A (mixture)", "mw": None, "volatility": "base", "use": "FR", "notes": "Leather reconstruction. Typically a blend of IBQ, birch tar, saffron, suede aldehydes."},

    # ========================================================================
    # ALDEHYDIC FAMILY
    # ========================================================================
    {"name": "Aldehyde C-12 MOF (2-Methyl Undecanal)", "cas": "110-41-8", "odor_descriptors": ["aldehydic", "soapy", "metallic", "amber", "waxy", "clean"], "odor_families": ["aldehydic", "amber"], "formula": "C12H24O", "mw": 184.32, "volatility": "top", "use": "FR", "notes": "Metallic-amber aldehyde. Key in Chanel No. 5 and aldehydic florals. Use at trace."},
    {"name": "Aldehyde C-8 (Octanal)", "cas": "124-13-0", "odor_descriptors": ["aldehydic", "fatty", "orange", "soapy", "waxy"], "odor_families": ["aldehydic", "citrus"], "formula": "C8H16O", "mw": 128.21, "volatility": "top", "use": "FL/FR", "notes": "Fatty-orange aldehyde. Used in citrus reconstructions for 'juice' effect."},
    {"name": "Aldehyde C-16 (Strawberry Aldehyde, Ethyl Methyl Phenylglycidate)", "cas": "77-83-8", "odor_descriptors": ["strawberry", "fruity", "sweet", "caramel", "gourmand"], "odor_families": ["fruity", "gourmand"], "formula": "C12H14O3", "mw": 206.24, "volatility": "heart", "use": "FL/FR", "notes": "Despite 'aldehyde' name, it's a strawberry note. Not actually an aldehyde chemically. Key in strawberry reconstructions."},

    # ========================================================================
    # EARTHY FAMILY
    # ========================================================================
    {"name": "Oakmoss Absolute (Natural)", "cas": "9000-50-4", "odor_descriptors": ["earthy", "mossy", "woody", "leathery", "seaweed", "deep"], "odor_families": ["earthy", "woody"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Evernia prunastri. THE chypre ingredient. IFRA severely restricted (sensitizer, atranyl aldehydes). Synthetic replacement: Evernyl. Devastated the chypre family."},
    {"name": "Evernyl (Veramoss)", "cas": "4707-47-5", "odor_descriptors": ["mossy", "woody", "earthy", "oakmoss", "fresh"], "odor_families": ["earthy", "woody"], "formula": "C10H12O4", "mw": 196.20, "volatility": "base", "use": "FR", "notes": "Synthetic oakmoss replacement. IFRA-compliant. Less rich than natural oakmoss but essential for modern chypre."},
    {"name": "Geosmin", "cas": "19700-21-1", "odor_descriptors": ["earthy", "petrichor", "soil", "damp", "musty", "fresh"], "odor_families": ["earthy"], "formula": "C12H22O", "mw": 182.30, "volatility": "top", "use": "FR", "notes": "The 'rain on dry earth' molecule (petrichor). Extremely powerful—used at parts-per-trillion. Found in beetroot. Key in earthy and mineral accords."},
    {"name": "Vetiverol", "cas": "68129-81-7", "odor_descriptors": ["earthy", "woody", "vetiver", "rooty", "green"], "odor_families": ["earthy", "woody"], "formula": "C15H24O", "mw": 220.35, "volatility": "base", "use": "FR", "notes": "Primary alcohol from vetiver oil. Earthy-woody-rooty."},
    {"name": "Patchoulol", "cas": "5986-55-0", "odor_descriptors": ["earthy", "patchouli", "woody", "camphoraceous", "sweet"], "odor_families": ["earthy", "woody"], "formula": "C15H26O", "mw": 222.37, "volatility": "base", "use": "FR", "notes": "Main component of patchouli oil (27-35%). Earthy-woody-sweet. Can be synthesized via biotech."},

    # ========================================================================
    # KEY NATATURAL EXTRACTS (Essential Oils & Absolutes)
    # ========================================================================
    {"name": "Rose Otto (Natural)", "cas": "8007-01-0", "odor_descriptors": ["floral", "rose", "honey", "winey", "spicy", "rich"], "odor_families": ["floral"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FL/FR", "notes": "Rosa damascena. Steam-distilled. ~60,000 roses for 30ml. Contains citronellol (50%+), geraniol (20%+), nerol, phenethyl alcohol, rose oxide, damascenone."},
    {"name": "Orange Blossom Absolute (Natural)", "cas": "72968-50-4", "odor_descriptors": ["floral", "orange blossom", "indolic", "sweet", "green", "narcotic"], "odor_families": ["floral", "green"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FL/FR", "notes": "Citrus aurantium flowers. Solvent-extracted. Richer and more indolic than neroli. Contains methyl anthranilate, indole, linalool."},
    {"name": "Mimosa Absolute (Natural)", "cas": "8022-98-6", "odor_descriptors": ["floral", "mimosa", "powdery", "green", "honey", "sweet"], "odor_families": ["floral", "powdery"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Acacia dealbata. Powdery-green-honey floral. Used in floral bouquets and powdery accords."},
    {"name": "Magnolia Flower Absolute (Natural)", "cas": "N/A", "odor_descriptors": ["floral", "magnolia", "lemon", "fresh", "sweet", "creamy"], "odor_families": ["floral", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Magnolia grandiflora. Lemon-cream-floral. Contains linalool, methyl anthranilate."},
    {"name": "Ambrette Seed Absolute (Natural)", "cas": "8015-62-1", "odor_descriptors": ["musk", "floral", "warm", "fruity", "skin", "ambrette"], "odor_families": ["musky", "floral"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Hibiscus abelmoschus. The only natural plant musk. Contains ambrettolide. Very expensive. Fruity-floral-musk."},
    {"name": "Opoponax Resinoid (Natural)", "cas": "8021-36-1", "odor_descriptors": ["balsamic", "sweet", "woody", "amber", "warm", "spicy"], "odor_families": ["amber", "spicy"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Commiphora erythraea. Sweet balsamic-amber. Key in oriental and amber accords."},
    {"name": "Elemi Resinoid (Natural)", "cas": "8023-89-0", "odor_descriptors": ["balsamic", "fresh", "lemony", "peppery", "incense", "woody"], "odor_families": ["amber", "citrus"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FR", "notes": "Canarium luzonicum. Fresh-lemony-balsamic. Bridge between citrus top and incense base. Used in incense accords."},
    {"name": "Cistus Labdanum Oil (Natural)", "cas": "89997-74-0", "odor_descriptors": ["amber", "labdanum", "warm", "resinous", "animalic", "rich"], "odor_families": ["amber", "leathery"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Steam-distilled Cistus ladanifer. More ambery than labdanum absolute. Rich warm amber. Key in amber and chypre accords."},
    {"name": "Hay Absolute (Natural)", "cas": "N/A", "odor_descriptors": ["hay", "green", "sweet", "warm", "coumarinic", "dried"], "odor_families": ["green", "gourmand"], "formula": "N/A (natural)", "mw": None, "volatility": "heart", "use": "FR", "notes": "Dried grass/hay. Contains coumarin, benzaldehyde. Warm-sweet-green. Used in fougère and green accords."},
    {"name": "Beeswax Absolute (Natural)", "cas": "8012-89-3", "odor_descriptors": ["honey", "wax", "warm", "sweet", "floral", "rich"], "odor_families": ["gourmand", "amber"], "formula": "N/A (natural)", "mw": None, "volatility": "base", "use": "FR", "notes": "Apis mellifera wax. Honey-wax-warm. Adds warmth and honey nuances. Very tenacious."},

    # ========================================================================
    # KEY SYNTHETICS (Modern Workhorse Molecules)
    # ========================================================================
    {"name": "Karanal", "cas": "N/A", "odor_descriptors": ["aldehydic", "amber", "metallic", "clean", "fresh"], "odor_families": ["aldehydic", "amber"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "IFF. Aldehydic-amber-metallic. Modern aldehyde. Used in fresh-aldehydic compositions."},
    {"name": "Kohinool", "cas": "N/A", "odor_descriptors": ["woody", "amber", "dry", "powdery"], "odor_families": ["woody", "amber"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "IFF. Dry woody-amber. Modern Norlimbanol alternative."},
    {"name": "Koavone (Methyl Lavender Ketone)", "cas": "27710-82-3", "odor_descriptors": ["floral", "lavender", "herbal", "fresh", "fruity"], "odor_families": ["floral", "aromatic_herbal"], "formula": "C11H14O2", "mw": 178.23, "volatility": "heart", "use": "FR", "notes": "Lavender-fruity-floral. Used in fougère and floral-herbal accords."},
    {"name": "Dynascone 10", "cas": "56973-85-4", "odor_descriptors": ["green", "galbanum", "fresh", "fruity", "tropical"], "odor_families": ["green", "fruity"], "formula": "C11H18O", "mw": 166.26, "volatility": "top", "use": "FR", "notes": "Firmenich. Galbanum-green with fruity nuance. Modern galbanum alternative."},
    {"name": "Exaltone (Cyclopentadecanone)", "cas": "502-72-7", "odor_descriptors": ["musk", "warm", "animalic", "powdery", "elegant"], "odor_families": ["musky"], "formula": "C15H28O", "mw": 224.39, "volatility": "base", "use": "FR", "notes": "Macrocyclic musk ketone. Warm-animalic musk. More animalic than Exaltolide."},
    {"name": "Ambrox (Dihydro Ambroxide)", "cas": "70788-30-6", "odor_descriptors": ["ambergris", "woody", "warm", "dry", "mineral"], "odor_families": ["amber", "woody"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "Related to Ambroxan but more woody-dry. Used interchangeably in some formulations."},
    {"name": "Velivione", "cas": "N/A", "odor_descriptors": ["musk", "powdery", "velvety", "clean", "soft"], "odor_families": ["musky"], "formula": "N/A (proprietary)", "mw": None, "volatility": "base", "use": "FR", "notes": "Givaudan. Powdery-velvety musk. Soft, clean, elegant."},
    {"name": "Mefrosol", "cas": "N/A", "odor_descriptors": ["floral", "linden", "fresh", "sweet", "honey"], "odor_families": ["floral"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Linden/honey flower character. Fresh-sweet-floral."},
    {"name": "Rose Petal Nitrile", "cas": "N/A", "odor_descriptors": ["floral", "rose", "green", "fresh", "metallic"], "odor_families": ["floral", "green"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Green-metallic rose character. More diffusive than geraniol. Used in fresh rose accords."},
    {"name": "Peony Nitrile", "cas": "N/A", "odor_descriptors": ["floral", "peony", "green", "fresh", "rosy"], "odor_families": ["floral", "green"], "formula": "N/A (proprietary)", "mw": None, "volatility": "top", "use": "FR", "notes": "Peony flower character. Fresh-green-rosy."},
    {"name": "Triplal (2,4-Dimethyl-3-Cyclohexene Carboxaldehyde)", "cas": "68039-48-5", "odor_descriptors": ["green", "fresh", "leafy", "herbal", "sharp"], "odor_families": ["green"], "formula": "C9H14O", "mw": 138.21, "volatility": "top", "use": "FR", "notes": "Intense green-leafy character. Very powerful. Key in green and herbal accords."},
    {"name": "Menthol", "cas": "89-78-1", "odor_descriptors": ["minty", "fresh", "cool", "camphoraceous", "peppermint"], "odor_families": ["aromatic_herbal"], "formula": "C10H20O", "mw": 156.27, "volatility": "top", "use": "FL/FR", "notes": "Cool-minty. TRPM8 receptor activator (cold sensation). Key in mint and cooling accords."},
    {"name": "Carvone", "cas": "99-49-0", "odor_descriptors": ["minty", "spearmint", "caraway", "fresh", "herbal"], "odor_families": ["aromatic_herbal"], "formula": "C10H14O", "mw": 150.22, "volatility": "top", "use": "FL/FR", "notes": "Spearmint (l-carvone) or caraway (d-carvone). Enantiomers smell different. Key in mint and spice accords."},
    {"name": "Anethole", "cas": "104-46-1", "odor_descriptors": ["anise", "sweet", "licorice", "warm", "fresh"], "odor_families": ["spicy", "aromatic_herbal"], "formula": "C10H12O", "mw": 148.20, "volatility": "top", "use": "FL/FR", "notes": "Anise and licorice character. Found in anise, fennel, star anise. Key in pastis and anisic accords."},
    {"name": "Cumin Oil (Natural)", "cas": "8014-13-9", "odor_descriptors": ["spicy", "cumin", "warm", "earthy", "sweaty", "animalic"], "odor_families": ["spicy", "earthy"], "formula": "N/A (natural)", "mw": None, "volatility": "top", "use": "FL/FR", "notes": "Cuminum cyminum. Warm-spicy-sweaty. Contains cuminaldehyde. Key in oriental and exotic spice accords."},
    {"name": "Sclareolide", "cas": "564-20-5", "odor_descriptors": ["amber", "tobacco", "warm", "sweet", "dry"], "odor_families": ["amber", "leathery"], "formula": "C16H24O2", "mw": 248.36, "volatility": "base", "use": "FR", "notes": "Amber-tobacco character. Semi-synthetic from clary sage. Bridge to Ambroxan synthesis."},
    {"name": "Ambroxan from Sclareol", "cas": "6790-58-5", "odor_descriptors": ["ambergris", "warm", "woody", "mineral", "animalic"], "odor_families": ["amber", "woody"], "formula": "C16H28O", "mw": 236.40, "volatility": "base", "use": "FR", "notes": "Semi-synthetic Ambroxan. Derived from clary sage sclareol. More sustainable than from ambergris."},
]


def get_seed_molecules():
    """Return the full seed molecule database (core + extended)."""
    from knowledge.seed_molecules_extended import EXTENDED_MOLECULES
    return SEED_MOLECULES + EXTENDED_MOLECULES


def get_molecules_by_odor_family(family: str) -> list:
    """Return all seed molecules matching a given odor family."""
    all_mols = get_seed_molecules()
    return [m for m in all_mols if family in m.get("odor_families", [])]


def get_molecules_by_volatility(tier: str) -> list:
    """Return all seed molecules matching a volatility tier (top/heart/base)."""
    all_mols = get_seed_molecules()
    return [m for m in all_mols if m.get("volatility") == tier]


def get_molecule_by_cas(cas: str) -> dict:
    """Look up a molecule by CAS number."""
    for m in get_seed_molecules():
        if m.get("cas") == cas:
            return m
    return {}


def get_molecule_by_name(name: str) -> dict:
    """Look up a molecule by name (fuzzy match)."""
    name_lower = name.lower()
    for m in get_seed_molecules():
        if name_lower in m.get("name", "").lower():
            return m
    return {}
